import { Alproba, Cserkesz, Proba, Tema } from "../models/proba"

export const Cserkeszek: Cserkesz[] = [
    { uid: "KisJatek", name: "Kis játék", startAge: 5, endAge: 6 },
    { uid: "NagyJatek", name: "Nagy játék", startAge: 7, endAge: 9 },
    { uid: "Ujonc", name: "Újonc", startAge: 10, endAge: 10 },
    { uid: "Taborvero", name: "Táborverő", startAge: 11, endAge: 12 },
    { uid: "Portyazo", name: "Portyázó", startAge: 13, endAge: 14 },
    { uid: "Honfoglalo", name: "Honfoglaló", startAge: 15, endAge: 16 },
]

export const Probak: Proba[] = [
    { uid: "Macko", name: "Mackó próba", cserkeszUid: "KisJatek" },
    { uid: "Napsugar", name: "Napsugár próba", cserkeszUid: "KisJatek" },
    { uid: "Fenyo", name: "Fenyő próba", cserkeszUid: "KisJatek" },
    { uid: "Tulipan", name: "Tulipán próba", cserkeszUid: "KisJatek" },
    { uid: "Igeret", name: "Igéret próba", cserkeszUid: "NagyJatek" },
    { uid: "UgyesMokus", name: "Ügyes Mókus próba", cserkeszUid: "NagyJatek" },
    { uid: "Mehecske", name: "Méhecske próba", cserkeszUid: "NagyJatek" },
    { uid: "Torzs", name: "Törzs próba", cserkeszUid: "NagyJatek" },
    { uid: "Bagoly", name: "Bagoly próba", cserkeszUid: "NagyJatek" },
    { uid: "Nyil", name: "Nyil próba", cserkeszUid: "NagyJatek" },
    { uid: "MagyarCimer", name: "Magyar címer próba", cserkeszUid: "Ujonc" },
    { uid: "SzentKorona", name: "Szent Korona próba", cserkeszUid: "Ujonc" },
    { uid: "PirosSzalag", name: "Piros szalag próba", cserkeszUid: "Taborvero" },
    { uid: "FeherSzalag", name: "Fehér szalag próba", cserkeszUid: "Taborvero" },
    { uid: "ZoldSzalag", name: "Zöld szalag próba", cserkeszUid: "Taborvero" },
    { uid: "LegyResen", name: "Légy résen próba", cserkeszUid: "Taborvero" },
    { uid: "PirosLiliom", name: "Piros liliom próba", cserkeszUid: "Portyazo" },
    { uid: "FeherLiliom", name: "Fehér liliom próba", cserkeszUid: "Portyazo" },
    { uid: "ZoldLiliom", name: "Zöld liliom próba", cserkeszUid: "Portyazo" },
    { uid: "Liliom", name: "Liliom próba", cserkeszUid: "Portyazo" },
    { uid: "PirosKoszoru", name: "Piros koszorú próba", cserkeszUid: "Honfoglalo" },
    { uid: "FeherKoszoru", name: "Fehér koszorú próba", cserkeszUid: "Honfoglalo" },
    { uid: "ZoldKoszoru", name: "Zöld koszorú próba", cserkeszUid: "Honfoglalo" },
    { uid: "Koszoru", name: "Koszorú próba", cserkeszUid: "Honfoglalo" },
]

export const Temak: Tema[] = [
    { uid: "Cserkeszismeretek", name: "Cserkészismeretek", emoji: "⚜️" },
    { uid: "Vallas", name: "Vallás", emoji: "✝️" },
    { uid: "Jellemneveles", name: "Jellemnevelés", emoji: "🦸" },
    { uid: "Magyarsagismeret", name: "Magyarságismeret", emoji: "🇭🇺" },
    { uid: "Elsosegely", name: "Elsősegély", emoji: "🩹" },
    { uid: "Termeszetismeret", name: "Természetismeret", emoji: "🌿" },
    { uid: "Csomozas", name: "Csomózás", emoji: "🪢" },
    { uid: "Jeladas", name: "Jeladás", emoji: "🎌" },
    { uid: "Tajekozodas", name: "Tájékozódás", emoji: "🧭" },
    { uid: "Becsles", name: "Becslés", emoji: "📐" },
    { uid: "Taborozas", name: "Táborozás, szerszámok", emoji: "⛺" },
    { uid: "Tuzrakas", name: "Tűzrakás, főzés és sütés", emoji: "🔥" },
    { uid: "Testedzes", name: "Testedzés", emoji: "🤸" },
]

export const Alprobak: Alproba[] = [
    { uid: "AlapCserkesztudas", probaUid: "MagyarCimer", temaUid: "Cserkeszismeretek", name: "Alap cserkésztudás", pontok: ["El tudod énekelni a cserkészinduló 1. versszakát.", "Tudod a cserkész jelszót és tisztelgést.", "Le tudod rajzolni a cserkészliliomot."] },
    { uid: "Cserkesztorveny", probaUid: "MagyarCimer", temaUid: "Cserkeszismeretek", name: "Cserkésztörvény", pontok: ["Fejből el tudod mondani a cs. törvény 10 pontját."] },
    { uid: "MindennapiImak", probaUid: "MagyarCimer", temaUid: "Vallas", name: "Mindennapi imák", pontok: ["Egyedül el tudod mondani az étkezési imákat, a reggeli és az esti imát."] },
    { uid: "NapiJotett", probaUid: "MagyarCimer", temaUid: "Jellemneveles", name: "Napi jótett", pontok: ["Napi jótettedről beszámoltál az őrsödnek."] },
    { uid: "MagyarZaszloEsLobogo", probaUid: "MagyarCimer", temaUid: "Magyarsagismeret", name: "Magyar zászló és lobogó", pontok: ["Fejből le tudod rajzolni a zászlót és lobogót.", "Tudod, hogy mi a zászló színeinek jelentése."] },
    { uid: "MagyarCimer", probaUid: "MagyarCimer", temaUid: "Magyarsagismeret", name: "Magyar címer", pontok: ["Fejből le tudod rajzolni a magyar címert.", "Ismered a magyar címerben található szimbólumok jelentését."] },
    { uid: "FoldrajzMagyarorszag", probaUid: "MagyarCimer", temaUid: "Magyarsagismeret", name: "Földrajz", pontok: ["Magyarországot megtalálod a világtérképen. Ismered Magyarország fővárosát és még 4 várost."] },
    { uid: "FontosAdatok", probaUid: "MagyarCimer", temaUid: "Elsosegely", name: "Fontos adatok", pontok: ["Fejből tudod saját címedet és adataidat. Ismered a helyi mentők számát."] },
    { uid: "ViselkedesAzErdoben", probaUid: "MagyarCimer", temaUid: "Termeszetismeret", name: "Viselkedés az erdőben", pontok: ["Tudod hogyan kell viselkedni az erdőben (3)."] },
    { uid: "OtHelyiAllat", probaUid: "MagyarCimer", temaUid: "Termeszetismeret", name: "5 helyi állat", pontok: ["Ismered 5 helyi állat nyomát és életmódját."] },
    { uid: "AlapokEsKetCsomo", probaUid: "MagyarCimer", temaUid: "Csomozas", name: "Alapok és 2 csomó", pontok: ["Tudod a jó csomó 3 tulajdonságát.", "Tudod a halászcsomót és hogy mire használják.", "Tudod az egyszerű kettőst és használatát.", "Spárgát helyesen tudsz feltekerni."] },
    { uid: "HatSipjel", probaUid: "MagyarCimer", temaUid: "Jeladas", name: "6 sípjel", pontok: ["Ismered: gyülekező, vigyázz, előre, óvatosan, ide hozzám, sebesen."] },
    { uid: "KetKarjel", probaUid: "MagyarCimer", temaUid: "Jeladas", name: "2 karjel", pontok: ["Felismered a karjeleket: vigyázz, sorakozó."] },
    { uid: "SzelrozsaEsVilagtajak", probaUid: "MagyarCimer", temaUid: "Tajekozodas", name: "Szélrózsa és világtájak", pontok: ["Mondóka alapján ismered a fő irányokat."] },
    { uid: "TestmagassagSuly", probaUid: "MagyarCimer", temaUid: "Becsles", name: "Testmagasság, súly", pontok: ["Tudod a saját testmagasságodat és a súlyodat."] },
    { uid: "ZsebkesBisztonsag", probaUid: "MagyarCimer", temaUid: "Taborozas", name: "Zsebkés", pontok: ["Tudod zsebkésedet biztonságosan használni.", "Tudsz jó nyársat faragni szalonnasütéshez."] },
    { uid: "SutesSzabadTuzon", probaUid: "MagyarCimer", temaUid: "Tuzrakas", name: "Sütés szabad tűzön", pontok: ["Sütöttél szalonnát nyárson tűz felett."] },
    { uid: "Gyakorlatok3EgyeniTorna", probaUid: "MagyarCimer", temaUid: "Testedzes", name: "Gyakorlatok", pontok: ["Be tudsz mutatni 3 egyéni tornagyakorlatot."] },
    { uid: "UgyessegFaraMaszas", probaUid: "MagyarCimer", temaUid: "Testedzes", name: "Ügyesség", pontok: ["Fel tudsz mászni egy fára."] },
    { uid: "Kitartas1PercFutas", probaUid: "MagyarCimer", temaUid: "Testedzes", name: "Kitartás", pontok: ["Tudsz 1 percig futni."] },

    { uid: "CserkeszSzokasok", probaUid: "SzentKorona", temaUid: "Cserkeszismeretek", name: "Cserkész szokások", pontok: ["Tudod a cserkész köszöntést és kézfogást."] },
    { uid: "Fogadalom", probaUid: "SzentKorona", temaUid: "Cserkeszismeretek", name: "Fogadalom", pontok: ["Fejből tudod a cserkészfogadalom szövegét."] },
    { uid: "Egyenruha", probaUid: "SzentKorona", temaUid: "Cserkeszismeretek", name: "Egyenruha", pontok: ["Ismered a cserkész egyenruhát és jelvényeit."] },
    { uid: "AlakisagokSorakozas", probaUid: "SzentKorona", temaUid: "Cserkeszismeretek", name: "Alakiságok", pontok: ["Tudsz sorakozni (sorban, őrsben) és menetelni."] },
    { uid: "Ima", probaUid: "SzentKorona", temaUid: "Vallas", name: "Ima", pontok: ["Kívülről el tudod mondani a „Mi Atyánk” imát."] },
    { uid: "CserkesztorvenyEgyEsKet", probaUid: "SzentKorona", temaUid: "Jellemneveles", name: "Cserkésztörvény 1. & 2.", pontok: ["Saját szavaiddal és példával el tudod magyarázni"] },
    { uid: "TitkosBaratBaratno", probaUid: "SzentKorona", temaUid: "Jellemneveles", name: "Titkos barát / barátnő", pontok: ["Van titkos barátod és tudod, hogy ez mit jelent."] },
    { uid: "Nepdaltudas", probaUid: "SzentKorona", temaUid: "Magyarsagismeret", name: "Népdaltudás", pontok: ["5 népdalt el tudsz énekelni."] },
    { uid: "MagyarSzentKorona", probaUid: "SzentKorona", temaUid: "Magyarsagismeret", name: "Magyar Szent Korona", pontok: ["Tudod, hogy milyen a magyar Szent Korona és a koronázási jelvényeket is ismered."] },
    { uid: "FoldrajzKarpatMedence", probaUid: "SzentKorona", temaUid: "Magyarsagismeret", name: "Földrajz", pontok: ["Ismered a Kárpát-medence főbb vizeit(5) és hegyeit.", "Magyarországgal szomszédos országok."] },
    { uid: "KisSebekKezelese", probaUid: "SzentKorona", temaUid: "Elsosegely", name: "Kis sebek kezelése", pontok: ["Kis sebet sebtapasszal helyesen tudsz kezelni."] },
    { uid: "OtHelyiNoveny", probaUid: "SzentKorona", temaUid: "Termeszetismeret", name: "5 helyi növény", pontok: ["Ismersz 5 helyi növényt, gyümölcsét és tudod, hogy mire használják."] },
    { uid: "TermeszetvedelemSzabaly", probaUid: "SzentKorona", temaUid: "Termeszetismeret", name: "Természetvédelem", pontok: ["A helyi szabályoknak megfelelően szétválasztod és gyűjtöd a szemetet: Égethető, műanyag, üveg, fém, stb."] },
    { uid: "TaborozasiCsomok", probaUid: "SzentKorona", temaUid: "Csomozas", name: "Táborozási csomók", pontok: ["Tudod a sátorfeszítőt, a szorító nyolcast pedig 2 módon."] },
    { uid: "NyolcUtjelBotbolKretaval", probaUid: "SzentKorona", temaUid: "Jeladas", name: "8 útjel botból / krétával", pontok: ["Jó út, rossz út, hazamentem, menj haza, jó víz, rossz víz, levél x lépésre, vigyázz / veszély."] },
    { uid: "MitKellTennedHaEltevedsz", probaUid: "SzentKorona", temaUid: "Tajekozodas", name: "Mit kell tenned ha eltévedsz?", pontok: ["Tudod, hogy mit kell tenned ha lemaradsz az őrsödtől."] },
    { uid: "OnmeretekSajat1", probaUid: "SzentKorona", temaUid: "Becsles", name: "Önméretek", pontok: ["Saját méreteidet ismered: kis-, és nagy arasz, hüvelykujj, testmagasság, fesztáv, 1 láb,1 lépés, Hány lépes kell 10m-hez (vagy 10 yardhoz)?"] },
    { uid: "ZsebkesNyakkendoGyuru", probaUid: "SzentKorona", temaUid: "Taborozas", name: "Zsebkés", pontok: ["Tudsz zsebkéseddel nyakkendő gyűrűt faragni."] },
    { uid: "Varras", probaUid: "SzentKorona", temaUid: "Taborozas", name: "Varrás", pontok: ["Felvarrsz egy gombot."] },
    { uid: "HelyesGyujtas", probaUid: "SzentKorona", temaUid: "Tuzrakas", name: "Helyes gyújtás", pontok: ["Biztonságosan tudsz fáklyát gyújtani és kezelni."] },
    { uid: "Gyakorlatok3ParosTorna", probaUid: "SzentKorona", temaUid: "Testedzes", name: "Gyakorlatok", pontok: ["Be tudsz mutatni 3 páros tornagyakorlatot."] },
    { uid: "UgyessegKotelhid", probaUid: "SzentKorona", temaUid: "Testedzes", name: "Ügyesség", pontok: ["Kötélhídon át tudsz mászni."] },
    { uid: "Kitartas2PercFutas", probaUid: "SzentKorona", temaUid: "Testedzes", name: "Kitartás", pontok: ["Tudsz 2 percet futni."] },

    { uid: "OrsiSajatsagok", probaUid: "PirosSzalag", temaUid: "Cserkeszismeretek", name: "Őrsi sajátságok", pontok: ["Ismered őrsöd zászlóját, indulóját és csatakiáltását"] },
    { uid: "Probarendszer", probaUid: "PirosSzalag", temaUid: "Cserkeszismeretek", name: "Próbarendszer", pontok: ["Ismered a használt próbarendszert, (jelvényeit és követelményeit)."] },
    { uid: "AlakisagokMeneteles", probaUid: "PirosSzalag", temaUid: "Cserkeszismeretek", name: "Alakiságok", pontok: ["Menetelés és tisztelgés zászlóval."] },
    { uid: "Unnepek", probaUid: "PirosSzalag", temaUid: "Vallas", name: "Ünnepek", pontok: ["Tudod karácsony és húsvét jelentőségét, történetét. Ismered az ezekkel kapcsolatos magyar népszokásokat."] },
    { uid: "CserkesztorvenyHaromEsNegy", probaUid: "PirosSzalag", temaUid: "Jellemneveles", name: "Cserkésztörvény 3. & 4.", pontok: ["Saját szavaiddal és példával el tudod magyarázni."] },
    { uid: "KoszontesEsBemutatkozas", probaUid: "PirosSzalag", temaUid: "Jellemneveles", name: "Köszöntés és bemutatkozás", pontok: ["Tudsz helyesen köszönni és bemutatkozni."] },
    { uid: "Himnusz", probaUid: "PirosSzalag", temaUid: "Magyarsagismeret", name: "Himnusz", pontok: ["El tudod énekelni a Himnusz 1. versszakát."] },
    { uid: "TortenelemAttila", probaUid: "PirosSzalag", temaUid: "Magyarsagismeret", name: "Történelem", pontok: ["Tudod, ki volt Attila, ismersz 2 mondát életéből."] },
    { uid: "HunMagyarMondakor", probaUid: "PirosSzalag", temaUid: "Magyarsagismeret", name: "Hun-magyar mondakör", pontok: ["Tudod ki volt Hunor és Magor. El tudsz mondani 2 hun-magyar mondát."] },
    { uid: "FoldrajzOshaza", probaUid: "PirosSzalag", temaUid: "Magyarsagismeret", name: "Földrajz", pontok: ["Tudod, hogy mit neveznek Őshazának."] },
    { uid: "ElsosegelyAlapok", probaUid: "PirosSzalag", temaUid: "Elsosegely", name: "Elsősegély alapok", pontok: ["Tudod, hogy baleset esetén mit kell tenni. (Életet menteni, jelentést adni, biztosítani)."] },
    { uid: "Balesetjelentes", probaUid: "PirosSzalag", temaUid: "", name: "Balesetjelentés", pontok: ["Tudsz balesetet jelenteni: mi történt, hol, kivel, mikor, mi a helyzet?"] },
    { uid: "SzalkaOrrverzesVizholyag", probaUid: "PirosSzalag", temaUid: "Elsosegely", name: "Szálka, orrvérzés, vízhólyag", pontok: ["Tudod a szálka, orrvérzés és vízhólyag kezelését."] },
    { uid: "FurdesiSzabalyok", probaUid: "PirosSzalag", temaUid: "Elsosegely", name: "Fürdési szabályok", pontok: ["Ismered a fürdési szabályokat (6 db.)."] },
    { uid: "TizErdeiAllat", probaUid: "PirosSzalag", temaUid: "Termeszetismeret", name: "10 erdei állat", pontok: ["Ismersz 10 erdei állatot, nyomát és életmódját. MO: vaddisznó,őz,róka,nyúl,egér,mókus,borz,nyest,sün és a medve."] },
    { uid: "HaromszalasFonas", probaUid: "PirosSzalag", temaUid: "Csomozas", name: "Háromszálas fonás", pontok: ["Készítesz dísztárgyat háromszálas fonással."] },
    { uid: "RovasirasAlapok", probaUid: "PirosSzalag", temaUid: "Jeladas", name: "Rovásírás alapok", pontok: ["Ismered a rovásírás szabályait és eredetét.", "Fejből le tudod írni saját nevedet rovásírással."] },
    { uid: "TizLegfontosabbTerkepjel", probaUid: "PirosSzalag", temaUid: "Tajekozodas", name: "10 legfontosabb térképjel", pontok: ["Megtanulod: erdő, vasút, templom, folyó, főút, út, ösvény, épület, torony, tó térképjeleit."] },
    { uid: "Menetszabalyok", probaUid: "PirosSzalag", temaUid: "Tajekozodas", name: "Menetszabályok", pontok: ["Tudod a menetszabályokat (5db.)."] },
    { uid: "MegfigyeloJatek", probaUid: "PirosSzalag", temaUid: "Becsles", name: "Megfigyelő játék", pontok: ["Ismersz 3 Kim-játékot."] },
    { uid: "BaltaEsFureszHasznalata", probaUid: "PirosSzalag", temaUid: "Taborozas", name: "Balta és fűrész használata", pontok: ["Baltát és fűrészt szabályosan tudsz használni.", "Helyesen tudod azokat vinni és átadni."] },
    { uid: "Tuzszabalyok", probaUid: "PirosSzalag", temaUid: "Tuzrakas", name: "Tűzszabályok", pontok: ["El tudod mondani a tűzgyújtási szabályokat (5db.).", "Tudsz szabályosan tüzet rakni és meggyújtani."] },
    { uid: "GyakorlatokSzamhaboru", probaUid: "PirosSzalag", temaUid: "Testedzes", name: "Gyakorlatok", pontok: ["Ismered a számháború 5 fontos szabályát.", "Részt vettél 3 vasgyúró játékon."] },
    { uid: "UgyessegKuszas", probaUid: "PirosSzalag", temaUid: "Testedzes", name: "Ügyesség", pontok: ["Tudsz zaj nélkül kúszni és lopózkodni."] },
    { uid: "Kitartas3PercFutas", probaUid: "PirosSzalag", temaUid: "Testedzes", name: "Kitartás", pontok: ["Tudsz 3 percig futni (vagy 50 métert úszni, vagy 4 km-t kerékpározni)."] },

    { uid: "Csapat", probaUid: "FeherSzalag", temaUid: "Cserkeszismeretek", name: "Csapat", pontok: ["Ismered a csapatod számát és névadóját."] },
    { uid: "Vezetok", probaUid: "FeherSzalag", temaUid: "Cserkeszismeretek", name: "Vezetők", pontok: ["Tudod a cspk-d és őv-d nevét és tel. számát."] },
    { uid: "Cserkeszrangok", probaUid: "FeherSzalag", temaUid: "Cserkeszismeretek", name: "Cserkészrangok", pontok: ["Ismered a cs. rangok sorrendjét és jelvényeit."] },
    { uid: "BiPiNeve", probaUid: "FeherSzalag", temaUid: "Cserkeszismeretek", name: "BiPi", pontok: ["Ismered BiPi rendes nevét."] },
    { uid: "Templom", probaUid: "FeherSzalag", temaUid: "Vallas", name: "Templom", pontok: ["Ismered a templom berendezését és külső jeleit."] },
    { uid: "EgyhaziEnekek", probaUid: "FeherSzalag", temaUid: "Vallas", name: "Egyházi énekek", pontok: ["Tudsz 2 egyházi éneket."] },
    { uid: "CserkesztorvenyOtEsHat", probaUid: "FeherSzalag", temaUid: "Jellemneveles", name: "Cserkésztörvény 5. & 6.", pontok: ["Saját szavaiddal és példával el tudod magyarázni."] },
    { uid: "Jellemvonasok", probaUid: "FeherSzalag", temaUid: "Jellemneveles", name: "Jellemvonások", pontok: ["Tudsz példát mondani a következő tulajdonságokra: árulkodás, hazudás, bátorság, őszinteség."] },
    { uid: "KiszamoloVers", probaUid: "FeherSzalag", temaUid: "Magyarsagismeret", name: "Kiszámoló vers", pontok: ["El tudsz mondani legalább két kiszámoló verset."] },
    { uid: "HonfoglalasiMondak", probaUid: "FeherSzalag", temaUid: "Magyarsagismeret", name: "Honfoglalási mondák", pontok: ["El tudsz mondani 2 honfoglalási mondát."] },
    { uid: "Tortenelem859Tol", probaUid: "FeherSzalag", temaUid: "Magyarsagismeret", name: "Történelem 859 -", pontok: ["Tudod, hogy ki volt Árpád vezér?", "Tudod mi volt a vérszerződés és a honfoglalás."] },
    { uid: "FoldrajzKarpatHegy", probaUid: "FeherSzalag", temaUid: "Magyarsagismeret", name: "Földrajz:", pontok: ["Ismered a Kárpátmedence vizeit (10) és hegyeit (5)."] },
    { uid: "HaromszoguKendo", probaUid: "FeherSzalag", temaUid: "Elsosegely", name: "Háromszögű kendő", pontok: ["Használni tudod kéz, kar, láb és fej bekötésére."] },
    { uid: "EgesEsNapszuras", probaUid: "FeherSzalag", temaUid: "Elsosegely", name: "Égés és napszúrás", pontok: ["Tudod mit kell tenni égésnél és napszúrásnál."] },
    { uid: "EgyeniHigieniaMosakodas", probaUid: "FeherSzalag", temaUid: "", name: "Egyéni higiénia", pontok: ["Tudsz lavórban mosakodni (Tetőtől talpig!).", "Csajkádat rendesen el tudod mosogatni."] },
    { uid: "TizFaIsmerete", probaUid: "FeherSzalag", temaUid: "Termeszetismeret", name: "10 fa ismerete.", pontok: ["Megismered kinézetéről (levél, virág, stb.) és tudod, hogy mire jó.", "( MO: bükk, tölgy, akác, nyír, hárs, lucfenyő és vörösfenyő, alma, dió, cseresznye)"] },
    { uid: "Hurkok", probaUid: "FeherSzalag", temaUid: "Csomozas", name: "Hurkok", pontok: ["Használni tudod az egyszerű állóhurkot, sváb hurkot és a csúszó hurkot."] },
    { uid: "RovasirasNeved", probaUid: "FeherSzalag", temaUid: "Jeladas", name: "Rovásírás", pontok: ["Rovásírással felhímzed vagy faragod a nevedet."] },
    { uid: "Terkepfajtak", probaUid: "FeherSzalag", temaUid: "Tajekozodas", name: "Térképfajták", pontok: ["Ismered a városi- és autó-térkép sajátosságait, valamint ha körzetedben ismert, a turistatérképét."] },
    { uid: "EszakIranyIranytuvel", probaUid: "FeherSzalag", temaUid: "Tajekozodas", name: "Észak irány iránytűvel", pontok: ["Iránytűvel pontosan megmutatod észak irányát."] },
    { uid: "HolVagyATerkepen", probaUid: "FeherSzalag", temaUid: "Tajekozodas", name: "Hol vagy a térképen?", pontok: ["Felismered, hogy hol állsz a térképen."] },
    { uid: "TerkepMeretarany", probaUid: "FeherSzalag", temaUid: "Tajekozodas", name: "Térkép méretarány", pontok: ["Tudod mit jelent 1:25 000, 1:50 000, 1:100 000."] },
    { uid: "TerkepBetajolas", probaUid: "FeherSzalag", temaUid: "Tajekozodas", name: "Térkép betájolás", pontok: ["Betájolod a térképet észak irányába."] },
    { uid: "AlapmeretekBecslese", probaUid: "FeherSzalag", temaUid: "Becsles", name: "Alapméretek becslése", pontok: ["10 % pontossággal megmondod, hogy mennyi 1m, 10 cm (vagy 1 láb, egy yard, 1 hüvelyk)."] },
    { uid: "KisSator", probaUid: "FeherSzalag", temaUid: "", name: "Kis sátor (vagy őrsi sátor)", pontok: ["Fel tudod állítani, lebontani és becsomagolni."] },
    { uid: "Satorcovek", probaUid: "FeherSzalag", temaUid: "", name: "Sátorcövek", pontok: ["Tudsz cöveket beverni, faragsz fából pótcöveket."] },
    { uid: "SzemelyesCsomagolas", probaUid: "FeherSzalag", temaUid: "Taborozas", name: "Személyes csomagolás", pontok: ["Hátizsákot csomagolsz egy hétvégére.", "Írd fel az egyéni felszerelési tárgyak listáját."] },
    { uid: "Satorrend", probaUid: "FeherSzalag", temaUid: "Taborozas", name: "Sátorrend", pontok: ["Sátorban is rendben tudod tartani a dolgaidat."] },
    { uid: "TuzeloFak", probaUid: "FeherSzalag", temaUid: "Tuzrakas", name: "Tüzelő fák", pontok: ["Ismered és gyűjtesz tüzelésre alkalmas fákat.", "Tudod mi a gyújtós."] },
    { uid: "Gyakorlatok2Korjatek", probaUid: "FeherSzalag", temaUid: "Testedzes", name: "Gyakorlatok", pontok: ["Bemutatsz 2 népi körjátékot és 3 labdajátékot."] },
    { uid: "UgyessegNyil", probaUid: "FeherSzalag", temaUid: "Testedzes", name: "Ügyesség", pontok: ["Íjjal és nyíllal célba lősz."] },
    { uid: "Kitartas4PercetFutni", probaUid: "FeherSzalag", temaUid: "Testedzes", name: "Kitartás", pontok: ["Tudsz 4 percet futni, (vagy 100 métert úszni, vagy 6 km-t kerékpározni)."] },

    { uid: "KMCsSzKeruletek", probaUid: "ZoldSzalag", temaUid: "Cserkeszismeretek", name: "KMCsSz - kerületek", pontok: ["Ismered körzetedet, kerületedet és a Szövetséget."] },
    { uid: "ACserkeszetRendje", probaUid: "ZoldSzalag", temaUid: "Cserkeszismeretek", name: "A cserkészet rendje", pontok: ["Tudod, hogy mi az őrsi rendszer alapgondolata."] },
    { uid: "VallasiIsmeretek", probaUid: "ZoldSzalag", temaUid: "Vallas", name: "Vallási ismeretek", pontok: ["Jézus életéből ismersz egy példát.", "Tudsz papoknak helyesen köszönni.", "Első áldozás, bérmálás és konfirmálás."] },
    { uid: "CserkesztorvenyHetEsNyolc", probaUid: "ZoldSzalag", temaUid: "Jellemneveles", name: "Cserkésztörvény 7. & 8.", pontok: ["Saját szavaiddal és példával el tudod magyarázni."] },
    { uid: "ViselkedesIllemszabalyok", probaUid: "ZoldSzalag", temaUid: "Jellemneveles", name: "Viselkedés, illemszabályok", pontok: ["Tudod, hogyan kell viselkedni társaságban, idősebbekkel szemben, étkezésnél, stb."] },
    { uid: "NemzetiUnnepek", probaUid: "ZoldSzalag", temaUid: "Magyarsagismeret", name: "Nemzeti ünnepek", pontok: ["Ismersz 3 nemzeti ünnepet."] },
    { uid: "CsaladiUnnepek", probaUid: "ZoldSzalag", temaUid: "Magyarsagismeret", name: "Családi ünnepek", pontok: ["Ismered a családi ünnepeket (5)."] },
    { uid: "Tortenelem1000Tol", probaUid: "ZoldSzalag", temaUid: "Magyarsagismeret", name: "Történelem 1000 -", pontok: ["Ismered Géza fejedelem és Szent István tetteit."] },
    { uid: "FoldrajzDunantulVaros", probaUid: "ZoldSzalag", temaUid: "Magyarsagismeret", name: "Földrajz", pontok: ["Dunántúl: Jellegzetességei, főbb városai, stb."] },
    { uid: "Csipes", probaUid: "ZoldSzalag", temaUid: "Elsosegely", name: "Csípés", pontok: ["Tudod, hogy csípésnél mit kell tenni."] },
    { uid: "Kullancs", probaUid: "ZoldSzalag", temaUid: "Elsosegely", name: "Kullancs", pontok: ["Tudod, hogy mit csinálsz kullancscsípésnél."] },
    { uid: "GyomorrontasHanyas", probaUid: "ZoldSzalag", temaUid: "Elsosegely", name: "Gyomorrontás, hányás", pontok: ["Tudod kezelni a hasfájást, hányást, hasmenést."] },
    { uid: "Mergezes", probaUid: "ZoldSzalag", temaUid: "Elsosegely", name: "Mérgezés", pontok: ["Tudod, hogy mérgezésnél mit kell tenni."] },
    { uid: "OtHelyiMadar", probaUid: "ZoldSzalag", temaUid: "Termeszetismeret", name: "5 helyi madár", pontok: ["Ismersz 5 madarat repülésben és az életmódját. (MO: gólya, bagoly, veréb, rigó és fecske)"] },
    { uid: "HaromRagadozoMadar", probaUid: "ZoldSzalag", temaUid: "Termeszetismeret", name: "3 ragadozó madár", pontok: ["Ismered árnyékképét repülésben és az életmódját (MO: egerészölyv, kánya és sólyom)"] },
    { uid: "Kotelletra", probaUid: "ZoldSzalag", temaUid: "Csomozas", name: "Kötéllétra", pontok: ["Tudod, hogy melyik csomó kell a kötéllétrához.", "Tudsz egy kötéllétrát építeni."] },
    { uid: "KotelFeltekeres", probaUid: "ZoldSzalag", temaUid: "Csomozas", name: "Kötél feltekerés", pontok: ["Kötelet helyesen fel tudsz szedni (tekerni)."] },
    { uid: "RovasirasAbc", probaUid: "ZoldSzalag", temaUid: "Jeladas", name: "Rovásírás", pontok: ["Fejből tudod a rovásírás abc-t."] },
    { uid: "EszakiIranyIranytuNelkul", probaUid: "ZoldSzalag", temaUid: "Tajekozodas", name: "Északi irány iránytű nélkül", pontok: ["Ismersz 3 módot az északi irány megállapítására. (Nap és óra, Nap és árnyék, Göncölszekér vagy Dél keresztje)."] },
    { uid: "TajoloHasznalata", probaUid: "ZoldSzalag", temaUid: "Tajekozodas", name: "Tájoló használata", pontok: ["Iránytűvel bármilyen irányt meg tudsz állapítani."] },
    { uid: "Arak", probaUid: "ZoldSzalag", temaUid: "Becsles", name: "Árak", pontok: ["Becsüld meg egyes tárgyak bolti árát. (5db)."] },
    { uid: "PenzBeosztasa", probaUid: "ZoldSzalag", temaUid: "Becsles", name: "Pénz beosztása", pontok: ["Minél olcsóbban uzsonnát veszel az őrsödnek."] },
    { uid: "ZsebkesElesites", probaUid: "ZoldSzalag", temaUid: "Taborozas", name: "Zsebkés", pontok: ["Megélesíted a zsebkésedet."] },
    { uid: "Csajkazsak", probaUid: "ZoldSzalag", temaUid: "Taborozas", name: "Csajkazsák", pontok: ["Varrsz egy csajkazsákot."] },
    { uid: "Teafozes", probaUid: "ZoldSzalag", temaUid: "Taborozas", name: "Teafőzés", pontok: ["Építesz olyan főzőalkalmatosságot, amin teát főzöl."] },
    { uid: "Gyakorlatok3Korjatek", probaUid: "ZoldSzalag", temaUid: "Testedzes", name: "Gyakorlatok", pontok: ["Bemutatsz társaiddal 3 körjátékot."] },
    { uid: "UgyessegKotelLetra", probaUid: "ZoldSzalag", temaUid: "Testedzes", name: "Ügyesség", pontok: ["Tudsz kötéllétrán mászni.", "Elvégzel egyensúlygyakorlatokat."] },
    { uid: "Kitartas5PercFutas", probaUid: "ZoldSzalag", temaUid: "Testedzes", name: "Kitartás", pontok: ["Tudsz 5 percet futni (vagy 200 métert úszni, vagy 8 km-t kerékpározni)."] },

    { uid: "CserkesztortenelemBiPi", probaUid: "LegyResen", temaUid: "Cserkeszismeretek", name: "Cserkésztörténelem", pontok: ["Ismered Bipi életét és főbb jelszavait.", "Ismered a cserkésztörténet főbb eseményeit (1907, 1933, 1948).", "Ismered a leánycserkészet történetét (Pax Ting)."] },
    { uid: "SzabadImadkozas", probaUid: "LegyResen", temaUid: "Vallas", name: "Szabad imádkozás", pontok: ["Tudsz saját szavaiddal imádkozni."] },
    { uid: "CserkesztorvenyKilencEsTiz", probaUid: "LegyResen", temaUid: "Jellemneveles", name: "Cserkésztörvény 9. & 10.", pontok: ["Saját szavaiddal és példával el tudod magyarázni."] },
    { uid: "TaborozasiSzabalyok", probaUid: "LegyResen", temaUid: "Jellemneveles", name: "Táborozási szabályok", pontok: ["Ismered a táborozási szabályokat (7 db)."] },
    { uid: "HuszmagyarNepdal", probaUid: "LegyResen", temaUid: "Magyarsagismeret", name: "20 magyar népdal", pontok: ["20 népdalt fel tudsz sorolni és kérésre elénekelni."] },
    { uid: "Zaszlok", probaUid: "LegyResen", temaUid: "Magyarsagismeret", name: "Zászlók", pontok: ["Ismersz 3 történelmi zászlót."] },
    { uid: "Tortenelem1241Tol", probaUid: "LegyResen", temaUid: "Magyarsagismeret", name: "Történelem 1241 -", pontok: ["Tatárjárás, IV. Béla és a második honalapítás."] },
    { uid: "FoldrajzDelvidekVaros", probaUid: "LegyResen", temaUid: "Magyarsagismeret", name: "Földrajz", pontok: ["Délvidék: Jellegzetességei, főbb városai, stb."] },
    { uid: "Hordagy", probaUid: "LegyResen", temaUid: "Elsosegely", name: "Hordágy", pontok: ["Tudsz hordágyat készíteni és használni."] },
    { uid: "Nyomontes", probaUid: "LegyResen", temaUid: "Termeszetismeret", name: "Nyomöntés", pontok: ["Tudsz gipsszel állatnyomot önteni."] },
    { uid: "Nyomolvasas", probaUid: "LegyResen", temaUid: "Termeszetismeret", name: "Nyomolvasás", pontok: ["Találsz nyomokat és tudod azokat követni."] },
    { uid: "Allatmegfigyeles", probaUid: "LegyResen", temaUid: "Termeszetismeret", name: "Állatmegfigyelés", pontok: ["Szabadban figyelj meg 3 állatot."] },
    { uid: "Keresztkotes", probaUid: "LegyResen", temaUid: "Csomozas", name: "Keresztkötés", pontok: ["A keresztkötést meg tudod kötni."] },
    { uid: "KotelKarbantartasa", probaUid: "LegyResen", temaUid: "Csomozas", name: "Kötél karbantartása", pontok: ["Tudsz kötelet tárolni, tisztítani és szárítani."] },
    { uid: "NyolcUtjelKobolEsFubol", probaUid: "LegyResen", temaUid: "Jeladas", name: "8 útjel kőből és fűből", pontok: ["Jó út, rossz út, hazamentem, menj haza, jó víz, rossz víz, levél x lépésre, vigyázz / veszély."] },
    { uid: "VarosterkepHasznalata", probaUid: "LegyResen", temaUid: "Tajekozodas", name: "Várostérkép használata", pontok: ["Városban közlekedsz, adott helyeket megtalálsz."] },
    { uid: "TerkepEsIranytuEgy", probaUid: "LegyResen", temaUid: "Tajekozodas", name: "Térkép és iránytű 1.", pontok: ["Térkép alapján be tudod tájolni a menetirányt."] },
    { uid: "OnmeretekSajat2", probaUid: "LegyResen", temaUid: "Becsles", name: "Önméretek", pontok: ["Saját méreteidet ismered: kis-, és nagy arasz, hüvelykujj, testmagasság, fesztáv, 1 láb,1 lépés, Hány lépes kell 10m-hez (vagy 10 yardhoz)?"] },
    { uid: "AsoCsakany", probaUid: "LegyResen", temaUid: "Taborozas", name: "Ásó, csákány", pontok: ["Használod és rendben elrakod (zsírozás)."] },
    { uid: "TaboriHigieniaLatrina", probaUid: "LegyResen", temaUid: "Taborozas", name: "Tábori higiénia", pontok: ["Tudsz szabályos latrinát /pöcegödröt építeni."] },
    { uid: "PonyvaHasznalata", probaUid: "LegyResen", temaUid: "Taborozas", name: "Ponyva használata", pontok: ["Építesz ponyvából védőhelyet."] },
    { uid: "EgyszeruTaboriEpitmeny", probaUid: "LegyResen", temaUid: "Taborozas", name: "Egyszerű tábori építmény", pontok: ["Készítesz 1 tábori építményt (csajkafa, mosdó)."] },
    { uid: "Tuzfajtak", probaUid: "LegyResen", temaUid: "Tuzrakas", name: "Tűzfajták", pontok: ["Megrakod a gúla, máglya, és vadásztüzet.", "Ezekből az egyiket max. 3 gyufával meggyújtod."] },
    { uid: "Gyakorlatok2CsoportJetek", probaUid: "LegyResen", temaUid: "Testedzes", name: "Gyakorlatok", pontok: ["Bemutatsz 2 népi csoport játékot és 3 kötél játékot. "] },
    { uid: "UgyessegMeneteles", probaUid: "LegyResen", temaUid: "Testedzes", name: "Ügyesség", pontok: ["Tudod mi a cserkészmenetelés és alkalmazod."] },
    { uid: "Kitartas6PercFutas", probaUid: "LegyResen", temaUid: "Testedzes", name: "Kitartás", pontok: ["Tudsz 6 percet futni (vagy 300 métert úszni, vagy 10 km-t kerékpározni)."] },

    { uid: "CserkesztortenelemTeleki", probaUid: "PirosLiliom", temaUid: "Cserkeszismeretek", name: "Cserkésztörténelem", pontok: ["Tudod ki volt Gróf Teleki Pál és mi a hagyatéka."] },
    { uid: "Cserkeszszolgalat", probaUid: "PirosLiliom", temaUid: "Cserkeszismeretek", name: "Cserkészszolgálat", pontok: ["Tudod, hogy mi a cserkészszolgálat és őrsöddel cserkészszolgálatot tettél."] },
    { uid: "Kereszteles", probaUid: "PirosLiliom", temaUid: "Vallas", name: "Keresztelés", pontok: ["Tudod, hogy mit jelent és mi a célja a keresztelésnek."] },
    { uid: "DohanyzasEsAlkohol", probaUid: "PirosLiliom", temaUid: "Jellemneveles", name: "Dohányzás és alkohol", pontok: ["Részt vettél cigarettáról és alkoholról szóló vitán.", "(cs. törvény, tábori szabályok összefüggésében)"] },
    { uid: "Nepdal30", probaUid: "PirosLiliom", temaUid: "Magyarsagismeret", name: "Népdal", pontok: ["Ismersz 30 népdalt és kérésre el tudod énekelni"] },
    { uid: "OtHiresMagyar", probaUid: "PirosLiliom", temaUid: "Magyarsagismeret", name: "5 híres magyar", pontok: ["Ismersz 5 híres magyar személyt, és mesélni tudsz róla.(pl. feltaláló, utazó, művész, egyéb ...)"] },
    { uid: "Tortenelem1301Tol", probaUid: "PirosLiliom", temaUid: "Magyarsagismeret", name: "Történelem 1301 -", pontok: ["Anjou dinasztia: Károly Róbert és Nagy Lajos"] },
    { uid: "FoldrajzAlfoldVaros", probaUid: "PirosLiliom", temaUid: "Magyarsagismeret", name: "Földrajz", pontok: ["Alföld: Jellegzetességei, főbb városai, stb."] },
    { uid: "BalesetMegelozese", probaUid: "PirosLiliom", temaUid: "Elsosegely", name: "Baleset megelőzése", pontok: ["Tudsz 3 példát mondani a baleset elkerüléséhez."] },
    { uid: "FelhokEsJelentesuk", probaUid: "PirosLiliom", temaUid: "Termeszetismeret", name: "Felhők és jelentésük", pontok: ["Ismersz 4 felhőfajtát és hogy mit jelentenek. (bárány-, réteg- fátyol- és viharfelhő)"] },
    { uid: "Idojaras", probaUid: "PirosLiliom", temaUid: "Termeszetismeret", name: "Időjárás", pontok: ["Ismered a helyi időjárási viszonyokat."] },
    { uid: "Idojoslasok", probaUid: "PirosLiliom", temaUid: "Termeszetismeret", name: "Időjóslások", pontok: ["Ismersz népi időjóslásokat (4db)."] },
    { uid: "EgyMentocsomo", probaUid: "PirosLiliom", temaUid: "Csomozas", name: "1 Mentőcsomó", pontok: ["Egy mentőcsomót biztosan meg tudsz kötni."] },
    { uid: "FaramaszasHurokkal", probaUid: "PirosLiliom", temaUid: "Csomozas", name: "Fáramászás hurokkal", pontok: ["Tudsz hurok segítségével fára mászni."] },
    { uid: "TitkosIrasok", probaUid: "PirosLiliom", temaUid: "Jeladas", name: "Titkos írások", pontok: ["4 titkos írás:(pl. betűcsere, tükörírás, 5x5 kocka, Morze)", "Titkos írás citrommal."] },
    { uid: "MegTizTerkepjel", probaUid: "PirosLiliom", temaUid: "Tajekozodas", name: "Még 10 térképjel", pontok: ["Ismered és térképen megmutatod: vezeték, híd, mocsár, bokrok, egyes fák, sziklák, határok, forrás, barlang, temető."] },
    { uid: "MagassagiSzintvonalak", probaUid: "PirosLiliom", temaUid: "Tajekozodas", name: "Magassági szintvonalak", pontok: ["Tudod,hogy mit jelentenek, értelmüket és távolságukat."] },
    { uid: "HelyrajziTerkep", probaUid: "PirosLiliom", temaUid: "Tajekozodas", name: "Helyrajzi térkép", pontok: ["Eltalálsz a célba helyrajzi térkép segítségével."] },
    { uid: "Ido", probaUid: "PirosLiliom", temaUid: "Becsles", name: "Idő", pontok: ["1 perc hosszát megbecsülöd.", "Nap állásából megbecsülöd, hogy hány óra van."] },
    { uid: "Szerszamtarto", probaUid: "PirosLiliom", temaUid: "Taborozas", name: "Szerszámtartó", pontok: ["Építesz egy tábori szerszámtartót."] },
    { uid: "BaltaKarbantartasa", probaUid: "PirosLiliom", temaUid: "Taborozas", name: "Balta karbantartása", pontok: ["Megélesítesz egy baltát, laza fejét javítani tudod."] },
    { uid: "FureszKarbantartasa", probaUid: "PirosLiliom", temaUid: "Taborozas", name: "Fűrész karbantartása", pontok: ["Rossz fűrészlapot kicserélsz és bezsírozol."] },
    { uid: "SutesFoliaban", probaUid: "PirosLiliom", temaUid: "Tuzrakas", name: "Sütés fóliában", pontok: ["Parazsat készítesz és fóliában sütsz benne."] },
    { uid: "Gyakorlatok3Erogyakorlat", probaUid: "PirosLiliom", temaUid: "Testedzes", name: "Gyakorlatok", pontok: ["Bemutatsz 3 erőgyakorlatot."] },
    { uid: "Kitartas7PercFutas", probaUid: "PirosLiliom", temaUid: "Testedzes", name: "Kitartás", pontok: ["Tudsz 7 percet futni (vagy 400 métert úszni, vagy 12km-t kerékpározni)."] },

    { uid: "CserkesztortenelemSik", probaUid: "FeherLiliom", temaUid: "Cserkeszismeretek", name: "Cserkésztörténelem", pontok: ["Tudod ki volt Sík Sándor és tudsz tőle idézni."] },
    { uid: "Forum", probaUid: "FeherLiliom", temaUid: "Cserkeszismeretek", name: "Fórum", pontok: ["Tudod, hogy mi a Magyar Cserkészszövetségek Fóruma és, hogy kik a tagjai (8)."] },
    { uid: "EgyhaziUnnepek", probaUid: "FeherLiliom", temaUid: "Vallas", name: "Egyházi ünnepek", pontok: ["Ismersz 4 egyházi ünnepet és időpontját."] },
    { uid: "TvMobiltelefonJatek", probaUid: "FeherLiliom", temaUid: "Jellemneveles", name: "TV - mobiltelefon - játék", pontok: ["Részt vettél vitán ezekről a témákról."] },
    { uid: "Csalad", probaUid: "FeherLiliom", temaUid: "Jellemneveles", name: "Család", pontok: ["Őrsöddel részt vettél egy beszélgetésen szülő-gyermek viszonyáról. (lásd Lcs. könyv II. 14. oldal)"] },
    { uid: "Nepdal40", probaUid: "FeherLiliom", temaUid: "Magyarsagismeret", name: "Népdal", pontok: ["Ismersz 40 népdalt és kérésre el tudod énekelni."] },
    { uid: "MagyarUtazok", probaUid: "FeherLiliom", temaUid: "Magyarsagismeret", name: "Magyar utazók", pontok: ["Ismersz 2 utazót és tudod, hogy merre jártak."] },
    { uid: "MatyasKiralyMondak", probaUid: "FeherLiliom", temaUid: "Magyarsagismeret", name: "Mátyás király mondák", pontok: ["El tudsz mondani 2 mondát Mátyás királyról."] },
    { uid: "TizenotSzazad", probaUid: "FeherLiliom", temaUid: "Magyarsagismeret", name: "15. század", pontok: ["Ki voltHunyadi János és Hunyadi Mátyás?"] },
    { uid: "FoldrajzKarpataljaVaros", probaUid: "FeherLiliom", temaUid: "Magyarsagismeret", name: "Földrajz", pontok: ["Kárpátalja: jellegzetességei, főbb városai, stb."] },
    { uid: "FicamodasEsRandulas", probaUid: "FeherLiliom", temaUid: "Elsosegely", name: "Ficamodás és rándulás", pontok: ["Ellátsz egy megrándult vagy kificamodott bokát."] },
    { uid: "SebesultSzallitas", probaUid: "FeherLiliom", temaUid: "Elsosegely", name: "Sebesült szállítás", pontok: ["Tudsz sebesültet hordágy nélkül vinni."] },
    { uid: "EhetoNovenyek", probaUid: "FeherLiliom", temaUid: "Termeszetismeret", name: "Ehető növények", pontok: ["Ismersz 5 helyi ehető, vadon élő növényt. ( MO: szeder, málna, csipke, bodza és áfonya)"] },
    { uid: "MergezoNovenyek", probaUid: "FeherLiliom", temaUid: "Termeszetismeret", name: "Mérgező növények", pontok: ["Ismersz 3 helyi mérgező növényt és káros hatását. (MO: Gyöngyvirág, tiszafa és nadragulya)"] },
    { uid: "Viragok", probaUid: "FeherLiliom", temaUid: "Termeszetismeret", name: "Virágok", pontok: ["Ismersz 5 nálatok honos virágot. (MO: pitypang, százszorszép, ibolya, pipacs és napraforgó )"] },
    { uid: "ParhuzamosKotes", probaUid: "FeherLiliom", temaUid: "Csomozas", name: "Párhuzamos kötés", pontok: ["Meg tudod kötni a párhuzamos kötést.", "Tudsz 3-lábat építeni párhuzamos kötéssel."] },
    { uid: "Veszjelek", probaUid: "FeherLiliom", temaUid: "Jeladas", name: "Vészjelek", pontok: ["Füsttel, Síppal (SOS), tükör, helyi vészjelek."] },
    { uid: "UtiranyBetartasaIranytuvel", probaUid: "FeherLiliom", temaUid: "Tajekozodas", name: "Útirány betartása iránytűvel", pontok: ["Iránytűvel becélzott irányt tartod menet közben."] },
    { uid: "IranyAtviteleTerkepre", probaUid: "FeherLiliom", temaUid: "Tajekozodas", name: "Irány átvitele térképre", pontok: ["Egy becélzott irányt iránytűvel átviszel térképre."] },
    { uid: "Tavolsagbecsles", probaUid: "FeherLiliom", temaUid: "Becsles", name: "Távolságbecslés", pontok: ["Nagyobb távolságot tudsz 10% pontossággal becsülni: (arc, ember, embercsoport segítséggel).", "Távolságbecslés (pl. hüvelykujjal)."] },
    { uid: "PetroleumLampa", probaUid: "FeherLiliom", temaUid: "Taborozas", name: "Petróleum lámpa", pontok: ["Biztonságos használata, üvegcsere, kanóc csere."] },
    { uid: "Gazlampa", probaUid: "FeherLiliom", temaUid: "Taborozas", name: "Gázlámpa", pontok: ["Biztonságos használata, palack- és harisnya csere."] },
    { uid: "FozesBogracsban", probaUid: "FeherLiliom", temaUid: "Tuzrakas", name: "Főzés bográcsban", pontok: ["Elkészítesz egy egyszerű ételt bográcsban."] },
    { uid: "Gyakorlatok3Hajlekony", probaUid: "FeherLiliom", temaUid: "Testedzes", name: "Gyakorlatok", pontok: ["Bemutatsz 3 hajlékonysági gyakorlatot."] },
    { uid: "Meta", probaUid: "FeherLiliom", temaUid: "Testedzes", name: "Méta", pontok: ["Ismered a métát."] },
    { uid: "Kitartas8PercFutas", probaUid: "FeherLiliom", temaUid: "Testedzes", name: "Kitartás", pontok: ["Tudsz 8 percet futni (vagy 500 métert úszni, vagy 14 km-t kerékpározni)."] },

    { uid: "CserkesztortenelemBodnar", probaUid: "ZoldLiliom", temaUid: "Cserkeszismeretek", name: "Cserkésztörténelem", pontok: ["Tudod ki volt Bodnár Gábor és mit csinált."] },
    { uid: "MagyarSzentek", probaUid: "ZoldLiliom", temaUid: "Vallas", name: "Magyar szentek", pontok: ["El tudod mondani 3 magyar szent 1-1 legendáját."] },
    { uid: "Kabitoszer", probaUid: "ZoldLiliom", temaUid: "Jellemneveles", name: "Kábítószer", pontok: ["Részt vettél beszélgetésen a kábítószerről (a cs. törvény és szabályzat, valamint országod törvényének ismeretében)."] },
    { uid: "Segitokeszseg", probaUid: "ZoldLiliom", temaUid: "Jellemneveles", name: "Segítőkészség", pontok: ["Segítesz öregeknek (pl. Templomban, öregotthonban)."] },
    { uid: "Takarekossag", probaUid: "ZoldLiliom", temaUid: "Jellemneveles", name: "Takarékosság", pontok: ["Részt vettél beszélgetésen a pénzzel való gazdálkodásról és arról beszámolsz."] },
    { uid: "Nepdal50", probaUid: "ZoldLiliom", temaUid: "Magyarsagismeret", name: "Népdal", pontok: ["Ismersz 50 népdalt."] },
    { uid: "MagyarVarakTortenete", probaUid: "ZoldLiliom", temaUid: "Magyarsagismeret", name: "Magyar várak története", pontok: ["Ismered 3 magyar vár történetét."] },
    { uid: "MagyarSportolok", probaUid: "ZoldLiliom", temaUid: "Magyarsagismeret", name: "Magyar sportolók", pontok: ["Ismersz 2 sikeres magyar sportolót."] },
    { uid: "Tortenelem1526Tol", probaUid: "ZoldLiliom", temaUid: "Magyarsagismeret", name: "Történelem 1526-", pontok: ["Mesélj a mohácsi vészről, a török korszakról és a végvári harcokról (Eger, Szigetvár, ...)."] },
    { uid: "FoldrajzOrsegVaros", probaUid: "ZoldLiliom", temaUid: "Magyarsagismeret", name: "Földrajz", pontok: ["Őrség: Jellegzetességei, főbb városai, stb."] },
    { uid: "VerzesFajtak", probaUid: "ZoldLiliom", temaUid: "Elsosegely", name: "Vérzés fajták", pontok: ["Ismered a 3 vérzésfajtát és a teendőket."] },
    { uid: "Allatharapasok", probaUid: "ZoldLiliom", temaUid: "Elsosegely", name: "Állatharapások", pontok: ["Tudod, hogy állatharapásnál mit kell tenni."] },
    { uid: "Mentodoboz", probaUid: "ZoldLiliom", temaUid: "Elsosegely", name: "Mentődoboz", pontok: ["Ismered az őrsi mentődoboz tartalmát."] },
    { uid: "OtVedettAllat", probaUid: "ZoldLiliom", temaUid: "Termeszetismeret", name: "5 védett állat", pontok: ["Ismersz 5 helyi védett állatot és az életmódját. (MO: vízisikló, denevér, gyík, hód, hiúz)"] },
    { uid: "Allatfenykepezes", probaUid: "ZoldLiliom", temaUid: "Termeszetismeret", name: "Állatfényképezés", pontok: ["Lesből fényképezz erdei állatot."] },
    { uid: "DisztargyakNyakkendo", probaUid: "ZoldLiliom", temaUid: "Csomozas", name: "Dísztárgyak", pontok: ["Nyakkendő gyűrűt fonsz egy kiscserkésznek."] },
    { uid: "OldalEsKeresztmetszes", probaUid: "ZoldLiliom", temaUid: "Tajekozodas", name: "Oldal-, és keresztmetszés", pontok: ["Tudod az oldalmetszést, és hogy mire való.", "Ismered a keresztmetszést és hogy mire való."] },
    { uid: "Mennyisegek", probaUid: "ZoldLiliom", temaUid: "Becsles", name: "Mennyiségek", pontok: ["Becsülj 5 különböző mennyiséget (pl. hány ember van egy teremben, menyi víz van egy tartályban)."] },
    { uid: "NagySator", probaUid: "ZoldLiliom", temaUid: "Taborozas", name: "Nagy sátor", pontok: ["Felverés, bontás és csomagolás. Pl. konyhasátor.", "Sátorjavítás, szárítás, tárolás."] },
    { uid: "Tuzvedelem", probaUid: "ZoldLiliom", temaUid: "Tuzrakas", name: "Tűzvédelem", pontok: ["Tudod, mit kell tenni tűz esetén (5)."] },
    { uid: "Gyakorlatok3Lazito", probaUid: "ZoldLiliom", temaUid: "Testedzes", name: "Gyakorlatok", pontok: ["Bemutatsz 3 lazító gyakorlatot."] },
    { uid: "Kitartas9PercFutas", probaUid: "ZoldLiliom", temaUid: "Testedzes", name: "Kitartás", pontok: ["Tudsz 9 percet futni (vagy 600 métert úszni, vagy 16 km-t kerékpározni)."] },

    { uid: "HontalanSasok", probaUid: "Liliom", temaUid: "Cserkeszismeretek", name: "Hontalan Sasok", pontok: ["Tudod kik voltak a Hontalan Sasok és szerepüket."] },
    { uid: "Vezetokepzes", probaUid: "Liliom", temaUid: "Cserkeszismeretek", name: "Vezetőképzés", pontok: ["Ismered a KMCSSZ VK-rendszerét. Tudod mik a feltételek."] },
    { uid: "KotelessegunkIstenne", probaUid: "Liliom", temaUid: "Vallas", name: "Kötelességünk Istenne", pontok: ["El tudod magyarázni a cs. törvény 2. pontját „... kötelességét, mellyel Istennek ... tartozik”."] },
    { uid: "Szerelem", probaUid: "Liliom", temaUid: "Jellemneveles", name: "Szerelem", pontok: ["Részt vettél beszélgetésen a szerelemről (a Biblia szerint, a mai társadalomban, filmben, stb.)."] },
    { uid: "Baratsag", probaUid: "Liliom", temaUid: "Jellemneveles", name: "Barátság", pontok: ["Őrsöddel részt vettél beszélgetésen a Barátságról. (lásd Lcs. könyv II-70. oldal)"] },
    { uid: "Nepdal60", probaUid: "Liliom", temaUid: "Magyarsagismeret", name: "Népdal", pontok: ["Ismersz 60 népdalt."] },
    { uid: "MagyarTalalmanyok", probaUid: "Liliom", temaUid: "Magyarsagismeret", name: "Magyar találmányok", pontok: ["Ismersz 2 nagy magyar találmányt és feltalálóját."] },
    { uid: "TortenelemErdelyAranykor", probaUid: "Liliom", temaUid: "Magyarsagismeret", name: "Történelem", pontok: ["Erdély aranykora: Bethlen, Bocskai, Báthory", "A 3 részre szakadt ország."] },
    { uid: "FoldrajzErdelyVaros", probaUid: "Liliom", temaUid: "Magyarsagismeret", name: "Földrajz", pontok: ["Erdély: Jellegzetességei, főbb városai, stb."] },
    { uid: "Elsosegelynyujtas", probaUid: "Liliom", temaUid: "Elsosegely", name: "Elsősegélynyújtás", pontok: ["Tudsz elsősegélyt nyújtani az „1,2,3” szerint. (1 légzés, 2 vérzések, 3 vérkeringés)."] },
    { uid: "SinbeRakas", probaUid: "Liliom", temaUid: "Elsosegely", name: "Sínbe rakás", pontok: ["Tudsz eltört ujjat, kart vagy lábat sínbe rakni."] },
    { uid: "FeherEsVorosAjulas", probaUid: "Liliom", temaUid: "Elsosegely", name: "Fehér és vörös ájulás", pontok: ["Ismered az ájulási fajtákat (2), mi a teendő?"] },
    { uid: "SOKK", probaUid: "Liliom", temaUid: "Elsosegely", name: "SOKK", pontok: ["Az életveszélyes állapot felismerése és kezelése."] },
    { uid: "Oldalfektetes", probaUid: "Liliom", temaUid: "Elsosegely", name: "Oldalfektetés", pontok: ["Tudod, mikor kell a stabil oldalfekvést használni."] },
    { uid: "VedettNovenyek", probaUid: "Liliom", temaUid: "Termeszetismeret", name: "Védett növények", pontok: ["Ismersz 3 helyi védett növényt. (MO: encián, árvalányhaj, kankalin)"] },
    { uid: "TermeszetvedelmiTeruletek", probaUid: "Liliom", temaUid: "Termeszetismeret", name: "Természetvédelmi területek", pontok: ["Ismered a természetvédelmi területeken érvényes szabályokat."] },
    { uid: "Kotelhid", probaUid: "Liliom", temaUid: "Csomozas", name: "Kötélhíd", pontok: ["Feszítőcsomó kötélhídhoz.", "Ácshurok."] },
    { uid: "UtvonalTervezes", probaUid: "Liliom", temaUid: "Tajekozodas", name: "Útvonal tervezés", pontok: ["Térképen kiválasztod a legjobb portya útvonalat."] },
    { uid: "LeptekAtszamolas", probaUid: "Liliom", temaUid: "Tajekozodas", name: "Lépték átszámolás", pontok: ["Tudod, hogy pl. 4 cm az 1:50'000 térképen mennyi távolság a valóságban, és fordítva."] },
    { uid: "OnmeretekIsmetleseEsHasznalata", probaUid: "Liliom", temaUid: "Becsles", name: "Önméretek ismétlése és használata", pontok: ["Saját méreteidet ismered: kis-, és nagy arasz, hüvelykujj, testmagasság, fesztáv, 1 lépés, láb. Hány lépés 100 m (vagy 100 yard)?"] },
    { uid: "Gaztuzhely", probaUid: "Liliom", temaUid: "Taborozas", name: "Gáztűzhely", pontok: ["Gáz zsámolyt helyesen be tudsz gyújtani."] },
    { uid: "SutesKenyer", probaUid: "Liliom", temaUid: "Tuzrakas", name: "Sütés", pontok: ["Sütöttél kenyeret / pogácsát sütőben vagy tűzön."] },
    { uid: "FinomsagokTuzon", probaUid: "Liliom", temaUid: "Tuzrakas", name: "Finomságok tűzön", pontok: ["Sütsz egy finomságot tűzön."] },
    { uid: "Gyakorlatok2Kitartas", probaUid: "Liliom", temaUid: "Testedzes", name: "Gyakorlatok", pontok: ["Bemutatsz 2 kitartási gyakorlatot."] },
    { uid: "UgyessegCsoportos", probaUid: "Liliom", temaUid: "Testedzes", name: "Ügyesség", pontok: ["Ismersz 2 csoportos játékot."] },
    { uid: "Kitartas10PercFutas", probaUid: "Liliom", temaUid: "Testedzes", name: "Kitartás", pontok: ["Tudsz 10 percet futni (vagy 700 métert úszni, vagy 18 km-t kerékpározni)."] },

    { uid: "CserkesztortenelemNemeti", probaUid: "PirosKoszoru", temaUid: "Cserkeszismeretek", name: "Cserkésztörténelem", pontok: ["Tudod, hogy kik voltak Dr. Némethy György és Dr. Mattyasovszky-Zsolnay Miklós."] },
    { uid: "ATizParancsolatSzovege", probaUid: "PirosKoszoru", temaUid: "Cserkeszismeretek", name: "A 10 parancsolat szövege", pontok: ["Ismered a 10 parancsolat szövegét."] },
    { uid: "VallasosBeszelgetes", probaUid: "PirosKoszoru", temaUid: "Vallas", name: "Vallásos beszélgetés", pontok: ["Részt vettél vallásos témájú beszélgetésen.", "(lásd Lcs. könyv II.- 184 oldal)"] },
    { uid: "CserkesziesViselkedesReszlet", probaUid: "PirosKoszoru", temaUid: "Jellemneveles", name: "Cserkészies viselkedés", pontok: ["Példával részletezd: segítőkész, lusta."] },
    { uid: "VitaTargyilakos", probaUid: "PirosKoszoru", temaUid: "Jellemneveles", name: "Vita", pontok: ["Tudsz vitában tárgyilagosan érvelni."] },
    { uid: "Nepdal70", probaUid: "PirosKoszoru", temaUid: "Magyarsagismeret", name: "Népdal", pontok: ["Ismersz 70 népdalt."] },
    { uid: "MagyarFesto", probaUid: "PirosKoszoru", temaUid: "Magyarsagismeret", name: "Magyar festő", pontok: ["Ismersz 2 festőt és leghíresebb képeiket."] },
    { uid: "NyelvtaniJatekok", probaUid: "PirosKoszoru", temaUid: "Magyarsagismeret", name: "Nyelvtani játékok", pontok: ["Készítesz nyelvtani játékot."] },
    { uid: "TortenelemRakoci", probaUid: "PirosKoszoru", temaUid: "Magyarsagismeret", name: "Történelem", pontok: ["II. Rákóczi Ferenc és a kuruc kor."] },
    { uid: "FoldrajzFelvidekVaros", probaUid: "PirosKoszoru", temaUid: "Magyarsagismeret", name: "Földrajz", pontok: ["Felvidék: Jellegzetességei, főbb városai, stb."] },
    { uid: "Ivovizkeszites", probaUid: "PirosKoszoru", temaUid: "Elsosegely", name: "Ivóvízkészítés", pontok: ["Tudsz ivóvizet készíteni (szűrni, forralni)."] },
    { uid: "EgészsegesEtkezes", probaUid: "PirosKoszoru", temaUid: "Elsosegely", name: "Egészséges étkezés", pontok: ["Tudod hogyan kell egészségesen táplálkozni."] },
    { uid: "EgyeniHigieniaRuha", probaUid: "PirosKoszoru", temaUid: "Elsosegely", name: "Egyéni higiénia", pontok: ["Táborban kimosod a ruhádat."] },
    { uid: "Csillagkepek", probaUid: "PirosKoszoru", temaUid: "Termeszetismeret", name: "Csillagképek", pontok: ["Ismersz 8 csillagképet és legendáját."] },
    { uid: "KotelvegEldolgozas", probaUid: "PirosKoszoru", temaUid: "Csomozas", name: "Kötélvég eldolgozás", pontok: ["Kötélvég eldolgozása (2 mód)."] },
    { uid: "Kotelfajtak", probaUid: "PirosKoszoru", temaUid: "Csomozas", name: "Kötélfajták", pontok: ["Ismersz 3 kötélfajtát és hogy mire jók."] },
    { uid: "TajekozodasNapEsCsillag", probaUid: "PirosKoszoru", temaUid: "Tajekozodas", name: "Tájékozódás Nap és csillag", pontok: ["Tudsz a Nap és a csillagok segítségével tájékozódni."] },
    { uid: "Haromszogeles", probaUid: "PirosKoszoru", temaUid: "Becsles", name: "Háromszögelés", pontok: ["Magasság és folyó szélességének megállapítása."] },
    { uid: "TaboriHigieniaTaborozas", probaUid: "PirosKoszoru", temaUid: "Taborozas", name: "Tábori higiénia", pontok: ["Tudod, hogy mire kell táborozásnál ügyelni."] },
    { uid: "Illesztes", probaUid: "PirosKoszoru", temaUid: "Tuzrakas", name: "Illesztés", pontok: ["Tudsz fűrésszel és baltával fákat illeszteni."] },
    { uid: "MaglyatuzMegrakasa", probaUid: "PirosKoszoru", temaUid: "Tuzrakas", name: "Máglyatűz megrakása", pontok: ["Megraktál és tápláltál egy tábortüzet."] },
    { uid: "KulonlegesGyujtasmodok", probaUid: "PirosKoszoru", temaUid: "Tuzrakas", name: "Különleges gyújtásmódok", pontok: ["Bemutatsz egy különleges gyújtásmódot."] },
    { uid: "Bemelegites", probaUid: "PirosKoszoru", temaUid: "Testedzes", name: "Bemelegítés", pontok: ["Tudsz bemelegítő gyakorlatokat és tudod, hogy mire jók."] },
    { uid: "ReggeliTorna", probaUid: "PirosKoszoru", temaUid: "Testedzes", name: "Reggeli torna", pontok: ["Vezetsz egy reggeli tornát (kb. 10 perc)."] },
    { uid: "Kitartas11PercFutas", probaUid: "PirosKoszoru", temaUid: "Testedzes", name: "Kitartás", pontok: ["Tudsz 11 percet futni (vagy 800 métert úszni, vagy 20 km-t kerékpározni)."] },

    { uid: "MagyarCserkeszet", probaUid: "FeherKoszoru", temaUid: "Cserkeszismeretek", name: "Magyar cserkészet", pontok: ["Ismered a magyar cserkészet történetét."] },
    { uid: "HelyiMagyarsag", probaUid: "FeherKoszoru", temaUid: "Cserkeszismeretek", name: "Helyi magyarság", pontok: ["Ismered a helyi magyarság történetét."] },
    { uid: "HelyiCserkeszetMagyar", probaUid: "FeherKoszoru", temaUid: "Cserkeszismeretek", name: "Helyi cserkészet", pontok: ["Ismered a helyi magyar cserkészet történetét és főbb vezetőit."] },
    { uid: "Lelkigyakorlatok", probaUid: "FeherKoszoru", temaUid: "Vallas", name: "Lelkigyakorlatok", pontok: ["Csendes elmélkedésen veszel részt."] },
    { uid: "Szentiras", probaUid: "FeherKoszoru", temaUid: "Vallas", name: "Szentírás", pontok: ["Ismered a Biblia felépítését (Ószövetség, Újszövetség, négy evangélista, ...)."] },
    { uid: "CserkesziesViselkedesElmond", probaUid: "FeherKoszoru", temaUid: "Jellemneveles", name: "Cserkészies viselkedés:", pontok: ["Példával elmondod, hogy mi a „megbízhatóság”.", "Példával elmondod, hogy mi az „önmegtartóztatás”."] },
    { uid: "Eloadas", probaUid: "FeherKoszoru", temaUid: "Jellemneveles", name: "Előadás", pontok: ["Előadást tartasz (őrsödnek, csapatodnak, tábornak) egy általad választott témáról."] },
    { uid: "KotelessegtudatHaza", probaUid: "FeherKoszoru", temaUid: "Jellemneveles", name: "Kötelességtudat", pontok: ["Példákkal elmondod, hogy mi a kötelességünk a hazával és a magyarsággal szemben (fogadalom)."] },
    { uid: "Nepdal80", probaUid: "FeherKoszoru", temaUid: "Magyarsagismeret", name: "Népdalok", pontok: ["Ismersz 80 népdalt."] },
    { uid: "MagyarKoltok", probaUid: "FeherKoszoru", temaUid: "Magyarsagismeret", name: "Magyar költők", pontok: ["Ismersz 4 híres költőt és egy-egy művét."] },
    { uid: "Versmondas", probaUid: "FeherKoszoru", temaUid: "Magyarsagismeret", name: "Versmondás", pontok: ["Szavaltál egy komoly verset. (szavalóverseny)."] },
    { uid: "Tortenelem1848", probaUid: "FeherKoszoru", temaUid: "Magyarsagismeret", name: "Történelem", pontok: ["Ismered az 1848-as szabadságharc történetét."] },
    { uid: "FoldrajzKisalfoldVaros", probaUid: "FeherKoszoru", temaUid: "Magyarsagismeret", name: "Földrajz", pontok: ["Kisalföld: Jellegzetességei, főbb városai, stb."] },
    { uid: "NepiGyogyaszat", probaUid: "FeherKoszoru", temaUid: "Magyarsagismeret", name: "Népi gyógyászat", pontok: ["Ismersz házi recepteket (3)."] },
    { uid: "Mentes", probaUid: "FeherKoszoru", temaUid: "Elsosegely", name: "Mentés", pontok: ["Tudod, hogyan kell menteni jégből, tűzből és ha valakit áramütés ért."] },
    { uid: "Gyogynovenyek", probaUid: "FeherKoszoru", temaUid: "Elsosegely", name: "Gyógynövények", pontok: ["Ismersz 5 gyógynövényt és alkalmazásukat."] },
    { uid: "GPS", probaUid: "FeherKoszoru", temaUid: "Termeszetismeret", name: "GPS", pontok: ["Ismered a GPS működését."] },
    { uid: "Geocaching", probaUid: "FeherKoszoru", temaUid: "Termeszetismeret", name: "„Geocaching”", pontok: ["Eldugsz vagy megkeresel egy tárgyat."] },
    { uid: "TizAlapmeretek", probaUid: "FeherKoszoru", temaUid: "Becsles", name: "10 alapméretek", pontok: ["Becslést segítő méreteket ismersz. (pl. emelet, ingalengés, fa magassága, focipálya hossza, pénz mérete, stb.)"] },
    { uid: "TaboriEpitmenyek", probaUid: "FeherKoszoru", temaUid: "Taborozas", name: "Tábori építmények", pontok: ["Készítesz 1 nagy tábori építményt (pl. őrsi kaput, altábori kaput, vagy tábori konyhát.)."] },
    { uid: "BiwakAlvohelyEpites", probaUid: "FeherKoszoru", temaUid: "Taborozas", name: "Biwak (alvóhely) építés", pontok: ["Sátor nélkül kint alszol saját magad építette alvóhelyedben."] },
    { uid: "HaromFogasosEtelTuzon", probaUid: "FeherKoszoru", temaUid: "Tuzrakas", name: "3 fogásos étel tűzön", pontok: ["Készítesz 3-fogásos ételt tűzön vagy gázon."] },
    { uid: "Ijaszat", probaUid: "FeherKoszoru", temaUid: "Testedzes", name: "Íjászat", pontok: ["Tudsz íjjal célba lőni."] },
    { uid: "Kitartas12PercFutas", probaUid: "FeherKoszoru", temaUid: "Testedzes", name: "Kitartás", pontok: ["Tudsz 12 percet futni (vagy 900 métert úszni, vagy 25 km-t kerékpározni)."] },

    { uid: "HelyiCserkeszetNemzetkozi", probaUid: "ZoldKoszoru", temaUid: "Cserkeszismeretek", name: "Helyi cserkészet", pontok: ["Ismered a helyi cserkészetet. (pl. egyenruha, szokások)"] },
    { uid: "VilagcserkeszetMa", probaUid: "ZoldKoszoru", temaUid: "Cserkeszismeretek", name: "Világcserkészet ma", pontok: ["Hány cserkész van, utolsó Jamboree-k, WOSM."] },
    { uid: "EtikaiAlapelvek", probaUid: "ZoldKoszoru", temaUid: "Vallas", name: "Etikai alapelvek", pontok: ["Részt vettél etikai elvekről való beszélgetésen."] },
    { uid: "CserkesziesViselkedesJellemzes", probaUid: "ZoldKoszoru", temaUid: "Jellemneveles", name: "Cserkészies viselkedés", pontok: ["Mi jellemezi az igazi cserkészies viselkedést.", "Kiscserkészeknek bábozol erről."] },
    { uid: "VitaLogikus", probaUid: "ZoldKoszoru", temaUid: "Jellemneveles", name: "Vita", pontok: ["Vitában logikusan tudsz érvelni."] },
    { uid: "KotelessegtudatEmber", probaUid: "ZoldKoszoru", temaUid: "Jellemneveles", name: "Kötelességtudat", pontok: ["Példával elmondod, hogy mi a kötelességünk embertársainkkal szemben (fogadalom)."] },
    { uid: "Nepdal90", probaUid: "ZoldKoszoru", temaUid: "Magyarsagismeret", name: "Népdal", pontok: ["Ismersz 90 népdalt."] },
    { uid: "MagyarZeneszerzok", probaUid: "ZoldKoszoru", temaUid: "Magyarsagismeret", name: "Magyar zeneszerzők", pontok: ["Ismersz 2 híres zeneszerzőt."] },
    { uid: "Cikkiras", probaUid: "ZoldKoszoru", temaUid: "Magyarsagismeret", name: "Cikkírás", pontok: ["Írsz egy cikket, pl. újságba/ honlapra."] },
    { uid: "TortenelemVilaghaboru", probaUid: "ZoldKoszoru", temaUid: "Magyarsagismeret", name: "Történelem", pontok: ["Ismered Magyarország szerepét az I. és II. világháborúban."] },
    { uid: "FoldrajzTrianon", probaUid: "ZoldKoszoru", temaUid: "Magyarsagismeret", name: "Földrajz", pontok: ["Ismered a Trianoni békekötés következményeit."] },
    { uid: "Kigyoharapas", probaUid: "ZoldKoszoru", temaUid: "Elsosegely", name: "Kígyóharapás", pontok: ["Tudod, hogyan kell kígyóharapást kezelni."] },
    { uid: "MestersegesLegzes", probaUid: "ZoldKoszoru", temaUid: "Elsosegely", name: "Mesterséges légzés", pontok: ["Tudsz mesterséges légzést adni."] },
    { uid: "TizHelyiRovarEsHullo", probaUid: "ZoldKoszoru", temaUid: "Termeszetismeret", name: "10 helyi rovar és hüllő", pontok: ["Ismered nevüket és tudod, hogy melyik veszélyes / védett. (MO: méh, darázs, szitakötő, szarvasbogár, pók, béka, varangy, gyík, vipera, skorpió)"] },
    { uid: "TermeszetvedelemKezdemeny", probaUid: "ZoldKoszoru", temaUid: "Termeszetismeret", name: "Természetvédelem", pontok: ["Részt veszel egy természetvédelmi kezdeményezésen."] },
    { uid: "OtKulonlegesCsomo", probaUid: "ZoldKoszoru", temaUid: "Csomozas", name: "5 különleges csomó", pontok: ["Pruszik, ívelt kettős, nyolcas hurok, tolvaj csomó, kötélrövidítő."] },
    { uid: "TerepfelméresTerkeppel", probaUid: "ZoldKoszoru", temaUid: "Tajekozodas", name: "Terepfelmérés térképpel", pontok: ["Térkép alapján eldöntöd, hogy hol jó sátrat verni.", "A terepen kiválasztod a jó sátorhelyet."] },
    { uid: "Terkepvazlat", probaUid: "ZoldKoszoru", temaUid: "Tajekozodas", name: "Térképvázlat", pontok: ["Tudsz helyes térképvázlatot / látrajzot készíteni."] },
    { uid: "PenzBeosztas", probaUid: "ZoldKoszoru", temaUid: "Becsles", name: "Pénz beosztás", pontok: ["Vásárolj be egy kirándulásra minél olcsóbban."] },
    { uid: "PenzugyiElszamolas", probaUid: "ZoldKoszoru", temaUid: "Becsles", name: "Pénzügyi elszámolás", pontok: ["Tudsz helyesen bevételről - kiadásról elszámolni."] },
    { uid: "HasznalatiTargy", probaUid: "ZoldKoszoru", temaUid: "Taborozas", name: "Használati tárgy", pontok: ["Faragsz vagy varrsz egy tábori használati tárgyat."] },
    { uid: "AlapElelmiszerekAdagja", probaUid: "ZoldKoszoru", temaUid: "Tuzrakas", name: "Alap élelmiszerek adagja", pontok: ["5 alap élelmiszer személyenkénti mennyiségét ismered fejből."] },
    { uid: "FozesiAdagokKiszamitasa", probaUid: "ZoldKoszoru", temaUid: "Tuzrakas", name: "Főzési adagok kiszámítása", pontok: ["Nagy csoport számára ki tudod számítani a főzési adagokat."] },
    { uid: "NepiGyakorlatok", probaUid: "ZoldKoszoru", temaUid: "Testedzes", name: "Népi gyakorlatok", pontok: ["Tudsz néptáncot vagy ostorozni."] },
    { uid: "Kitartas15PercFutas", probaUid: "ZoldKoszoru", temaUid: "Testedzes", name: "Kitartás", pontok: ["Tudsz 15 percet futni (vagy 1000 métert úszni, vagy 30 km-t kerékpározni)."] },

    { uid: "Vandorcserkeszek", probaUid: "Koszoru", temaUid: "Cserkeszismeretek", name: "Vándorcserkészek", pontok: ["Ismered a vándor (rover) mozgalom célját és módszerét."] },
    { uid: "ZaszloterenImadkozol", probaUid: "Koszoru", temaUid: "Vallas", name: "Zászlótéren imádkozol", pontok: ["Zászló fel- vagy levonáskor mondasz saját imát."] },
    { uid: "BiPiMintPelda", probaUid: "Koszoru", temaUid: "Jellemneveles", name: "BiPi mint példa", pontok: ["Elmondod, miben lehet nekünk BiPi példa."] },
    { uid: "CserkeszJovo", probaUid: "Koszoru", temaUid: "Jellemneveles", name: "Cserkész jövő", pontok: ["Beszélgettek a cserkész jövőtökről."] },
    { uid: "VitaTapintatos", probaUid: "Koszoru", temaUid: "Jellemneveles", name: "Vita", pontok: ["Építő és tapintatos kritika."] },
    { uid: "MagyarNepdal", probaUid: "Koszoru", temaUid: "Magyarsagismeret", name: "Magyar népdal", pontok: ["Van listád 100 magyar népdalról és bármelyiket el is tudod énekelni."] },
    { uid: "Tortenelem1956", probaUid: "Koszoru", temaUid: "Magyarsagismeret", name: "Történelem", pontok: ["Ismered az 1956-os forradalom és szabadságharc történetét. Ismered Magyarország szerepét a vasfüggöny megszűnésében."] },
    { uid: "ElsosegelyTanfolyam", probaUid: "Koszoru", temaUid: "Elsosegely", name: "Elsősegély tanfolyam", pontok: ["Végezz el egy helyi elsősegély tanfolyamot és szerezd meg a hivatalos képesítést!"] },
    { uid: "Halak", probaUid: "Koszoru", temaUid: "Termeszetismeret", name: "Halak", pontok: ["Ismersz 5 halfajtát. (MO: pisztráng, csuka, harcsa, ponty, angolna.)"] },
    { uid: "Csomotabla", probaUid: "Koszoru", temaUid: "Csomozas", name: "Csomótábla", pontok: ["Készíts csomótáblát."] },
    { uid: "Maszas", probaUid: "Koszoru", temaUid: "Csomozas", name: "Mászás", pontok: ["Tudsz pruszikkal mászni."] },
    { uid: "Morzejelzes", probaUid: "Koszoru", temaUid: "Jeladas", name: "Morzejelzés", pontok: ["Tudsz morze üzenetet adni és fogadni morzekulcs segítségével."] },
    { uid: "MenetidoSzamitas", probaUid: "Koszoru", temaUid: "Tajekozodas", name: "Menetidő számítás", pontok: ["Portyára és kirándulásra ki tudod számítani a szükséges menetidőt, figyelembe véve a szintkülönbségeket is."] },
    { uid: "Munkaido", probaUid: "Koszoru", temaUid: "Becsles", name: "Munkaidő", pontok: ["Gyakorold egy feladat elvégzéséhez szükséges idő becslését (pl. csomagolás, főzés, ...)."] },
    { uid: "Taborepites", probaUid: "Koszoru", temaUid: "Taborozas", name: "Táborépítés", pontok: ["Tudod, mi tartozik egy jó táborhelyhez, és hogyan lehet azt berendezni."] },
    { uid: "DisztargyakNepi", probaUid: "Koszoru", temaUid: "Taborozas", name: "Dísztárgyak", pontok: ["Népi dísztárgyat készítesz (faragás, hímzés, bőrmunka, fonás)."] },
    { uid: "KonyhaHigienia", probaUid: "Koszoru", temaUid: "Tuzrakas", name: "Konyha higiénia", pontok: ["Tudsz tábori konyhában tisztaságot tartani. Élelem helyes tárolása."] },
    { uid: "MagyarKonyha", probaUid: "Koszoru", temaUid: "Tuzrakas", name: "Magyar konyha", pontok: ["Ismered a magyar konyha jellegzetességeit."] },
    { uid: "GyakorlatokTeljesitmeny", probaUid: "Koszoru", temaUid: "Testedzes", name: "Gyakorlatok", pontok: ["Teljesítmény túrán veszel részt."] },
    { uid: "UgyessegTajekozodas", probaUid: "Koszoru", temaUid: "Testedzes", name: "Ügyesség", pontok: ["Részt vettél tájékozódási futáson vagy néptáncon."] },
    { uid: "Kitartas20PercFutas", probaUid: "Koszoru", temaUid: "Testedzes", name: "Kitartás", pontok: ["Tudsz 20 percet futni (vagy 1200 métert úszni, vagy 50 km-t kerékpározni)."] },
]
