import { Alproba, Cserkesz, Proba, Tema } from "./proba-rendszer.models"

export const Cserkeszek = {
    Ujonc: new Cserkesz("Újonc", 10, 10),
    Taborvero: new Cserkesz("Táborverő", 11, 12),
    Portyazo: new Cserkesz("Portyázó", 13, 14),
    Honfoglalo: new Cserkesz("Honfoglaló", 15, 16),
}

export const Probak = {
    MagyarCimer: new Proba("Magyar címer próba", "MagyarCimerProba"),
    SzentKorona: new Proba("Szent Korona próba", "SzentKoronaProba"),
    PirosSzalag: new Proba("Piros szalag próba", "PirosSzalagProba"),
    FeherSzalag: new Proba("Fehér szalag próba", "FeherSzalagProba"),
    ZoldSzalag: new Proba("Zöld szalag próba", "ZoldSzalagProba"),
    LegyResen: new Proba("Légy résen próba", "LegyResenProba"),
    PirosLiliom: new Proba("Piros liliom próba", "PirosLiliomProba"),
    FeherLiliom: new Proba("Fehér liliom próba", "FeherLiliomProba"),
    ZoldLiliom: new Proba("Zöld liliom próba", "ZoldLiliomProba"),
    Liliom: new Proba("Liliom próba", "LiliomProba"),
    PirosKoszoru: new Proba("Piros koszorú próba", "PirosKoszoruProba"),
    FeherKoszoru: new Proba("Fehér koszorú próba", "FeherKoszoruProba"),
    ZoldKoszoru: new Proba("Zöld koszorú próba", "ZoldKoszoruProba"),
    Koszoru: new Proba("Koszorú próba", "KoszoruProba"),
}

export const Temak = {
    Cserkeszismeretek: new Tema("Cserkészismeretek", "⚜️"),
    Vallas: new Tema("Vallás", "✝️"),
    Jellemneveles: new Tema("Jellemnevelés", "🦸"),
    Magyarsagismeret: new Tema("Magyarságismeret", "🇭🇺"),
    Elsosegely: new Tema("Elsősegély", "🩹"),
    Termeszetismeret: new Tema("Természetismeret", "🌿"),
    Csomozas: new Tema("Csomózás", "🪢"),
    Jeladas: new Tema("Jeladás", "🎌"),
    Tajekozodas: new Tema("Tájékozódás", "🧭"),
    Becsles: new Tema("Becslés", "📐"),
    Taborozas: new Tema("Táborozás, szerszámok", "⛺"),
    Tuzrakas: new Tema("Tűzrakás, főzés és sütés", "🔥"),
    Testedzes: new Tema("Testedzés", "🤸"),
}

export const Alprobak = {
    AlapCserkesztudas: new Alproba("Alap cserkésztudás", ["El tudod énekelni a cserkészinduló 1. versszakát.", "Tudod a cserkész jelszót és tisztelgést.", "Le tudod rajzolni a cserkészliliomot."]),
    Cserkesztorveny: new Alproba("Cserkésztörvény", ["Fejből el tudod mondani a cs. törvény 10 pontját."]),
    MindennapiImak: new Alproba("Mindennapi imák", ["Egyedül el tudod mondani az étkezési imákat, a reggeli és az esti imát."]),
    NapiJotett: new Alproba("Napi jótett", ["Napi jótettedről beszámoltál az őrsödnek."]),
    MagyarZaszloEsLobogo: new Alproba("Magyar zászló és lobogó", ["Fejből le tudod rajzolni a zászlót és lobogót.", "Tudod, hogy mi a zászló színeinek jelentése."]),
    MagyarCimer: new Alproba("Magyar címer", ["Fejből le tudod rajzolni a magyar címert.", "Ismered a magyar címerben található szimbólumok jelentését."]),
    FoldrajzMagyarorszag: new Alproba("Földrajz", ["Magyarországot megtalálod a világtérképen. Ismered Magyarország fővárosát és még 4 várost."]),
    FontosAdatok: new Alproba("Fontos adatok", ["Fejből tudod saját címedet és adataidat. Ismered a helyi mentők számát."]),
    ViselkedesAzErdoben: new Alproba("Viselkedés az erdőben", ["Tudod hogyan kell viselkedni az erdőben (3)."]),
    OtHelyiAllat: new Alproba("5 helyi állat", ["Ismered 5 helyi állat nyomát és életmódját."]),
    AlapokEsKetCsomo: new Alproba("Alapok és 2 csomó", ["Tudod a jó csomó 3 tulajdonságát.", "Tudod a halászcsomót és hogy mire használják.", "Tudod az egyszerű kettőst és használatát.", "Spárgát helyesen tudsz feltekerni."]),
    HatSipjel: new Alproba("6 sípjel", ["Ismered: gyülekező, vigyázz, előre, óvatosan, ide hozzám, sebesen."]),
    KetKarjel: new Alproba("2 karjel", ["Felismered a karjeleket: vigyázz, sorakozó."]),
    SzelrozsaEsVilagtajak: new Alproba("Szélrózsa és világtájak", ["Mondóka alapján ismered a fő irányokat."]),
    TestmagassagSuly: new Alproba("Testmagasság, súly", ["Tudod a saját testmagasságodat és a súlyodat."]),
    ZsebkesBisztonsag: new Alproba("Zsebkés", ["Tudod zsebkésedet biztonságosan használni.", "Tudsz jó nyársat faragni szalonnasütéshez."]),
    SutesSzabadTuzon: new Alproba("Sütés szabad tűzön", ["Sütöttél szalonnát nyárson tűz felett."]),
    Gyakorlatok3EgyeniTorna: new Alproba("Gyakorlatok", ["Be tudsz mutatni 3 egyéni tornagyakorlatot."]),
    UgyessegFaraMaszas: new Alproba("Ügyesség", ["Fel tudsz mászni egy fára."]),
    Kitartas1PercFutas: new Alproba("Kitartás", ["Tudsz 1 percig futni."]),
    CserkeszSzokasok: new Alproba("Cserkész szokások", ["Tudod a cserkész köszöntést és kézfogást."]),
    Fogadalom: new Alproba("Fogadalom", ["Fejből tudod a cserkészfogadalom szövegét."]),
    Egyenruha: new Alproba("Egyenruha", ["Ismered a cserkész egyenruhát és jelvényeit."]),
    AlakisagokSorakozas: new Alproba("Alakiságok", ["Tudsz sorakozni (sorban, őrsben) és menetelni."]),
    Ima: new Alproba("Ima", ["Kívülről el tudod mondani a „Mi Atyánk” imát."]),
    CserkesztorvenyEgyEsKet: new Alproba("Cserkésztörvény 1. & 2.", ["Saját szavaiddal és példával el tudod magyarázni"]),
    TitkosBaratBaratno: new Alproba("Titkos barát / barátnő", ["Van titkos barátod és tudod, hogy ez mit jelent."]),
    Nepdaltudas: new Alproba("Népdaltudás", ["5 népdalt el tudsz énekelni."]),
    MagyarSzentKorona: new Alproba("Magyar Szent Korona", ["Tudod, hogy milyen a magyar Szent Korona és a koronázási jelvényeket is ismered."]),
    FoldrajzKarpat: new Alproba("Földrajz", ["Ismered a Kárpát-medence főbb vizeit(5) és hegyeit.", "Magyarországgal szomszédos országok."]),
    KisSebekKezelese: new Alproba("Kis sebek kezelése", ["Kis sebet sebtapasszal helyesen tudsz kezelni."]),
    OtHelyiNoveny: new Alproba("5 helyi növény", ["Ismersz 5 helyi növényt, gyümölcsét és tudod, hogy mire használják."]),
    TermeszetvedelemSzabaly: new Alproba("Természetvédelem", ["A helyi szabályoknak megfelelően szétválasztod és gyűjtöd a szemetet: Égethető, műanyag, üveg, fém, stb."]),
    TaborozasiCsomok: new Alproba("Táborozási csomók", ["Tudod a sátorfeszítőt, a szorító nyolcast pedig 2 módon."]),
    NyolcUtjelBotbolKretaval: new Alproba("8 útjel botból / krétával", ["Jó út, rossz út, hazamentem, menj haza, jó víz, rossz víz, levél x lépésre, vigyázz / veszély."]),
    MitKellTennedHaEltevedsz: new Alproba("Mit kell tenned ha eltévedsz?", ["Tudod, hogy mit kell tenned ha lemaradsz az őrsödtől."]),
    Onmeretek: new Alproba("Önméretek", ["Saját méreteidet ismered: kis-, és nagy arasz, hüvelykujj, testmagasság, fesztáv, 1 láb,1 lépés, Hány lépes kell 10m-hez (vagy 10 yardhoz)?"]),
    ZsebkesNyakkendoGyuru: new Alproba("Zsebkés", ["Tudsz zsebkéseddel nyakkendő gyűrűt faragni."]),
    Varras: new Alproba("Varrás", ["Felvarrsz egy gombot."]),
    HelyesGyujtas: new Alproba("Helyes gyújtás", ["Biztonságosan tudsz fáklyát gyújtani és kezelni."]),
    Gyakorlatok3ParosTorna: new Alproba("Gyakorlatok", ["Be tudsz mutatni 3 páros tornagyakorlatot."]),
    UgyessegKotelhid: new Alproba("Ügyesség", ["Kötélhídon át tudsz mászni."]),
    Kitartas2PercFutas: new Alproba("Kitartás", ["Tudsz 2 percet futni."]),
    OrsiSajatsagok: new Alproba("Őrsi sajátságok", ["Ismered őrsöd zászlóját, indulóját és csatakiáltását"]),
    Probarendszer: new Alproba("Próbarendszer", ["Ismered a használt próbarendszert, (jelvényeit és követelményeit)."]),
    AlakisagokMeneteles: new Alproba("Alakiságok", ["Menetelés és tisztelgés zászlóval."]),
    Unnepek: new Alproba("Ünnepek", ["Tudod karácsony és húsvét jelentőségét, történetét. Ismered az ezekkel kapcsolatos magyar népszokásokat."]),
    CserkesztorvenyHaromEsNegy: new Alproba("Cserkésztörvény 3. & 4.", ["Saját szavaiddal és példával el tudod magyarázni."]),
    KoszontesEsBemutatkozas: new Alproba("Köszöntés és bemutatkozás", ["Tudsz helyesen köszönni és bemutatkozni."]),
    Himnusz: new Alproba("Himnusz", ["El tudod énekelni a Himnusz 1. versszakát."]),
    TortenelemAttila: new Alproba("Történelem", ["Tudod, ki volt Attila, ismersz 2 mondát életéből."]),
    HunMagyarMondakor: new Alproba("Hun-magyar mondakör", ["Tudod ki volt Hunor és Magor. El tudsz mondani 2 hun-magyar mondát."]),
    FoldrajzOshaza: new Alproba("Földrajz", ["Tudod, hogy mit neveznek Őshazának."]),
    ElsosegelyAlapok: new Alproba("Elsősegély alapok", ["Tudod, hogy baleset esetén mit kell tenni. (Életet menteni, jelentést adni, biztosítani)."]),
    Balesetjelentes: new Alproba("Balesetjelentés", ["Tudsz balesetet jelenteni: mi történt, hol, kivel, mikor, mi a helyzet?"]),
    SzalkaOrrverzesVizholyag: new Alproba("Szálka, orrvérzés, vízhólyag", ["Tudod a szálka, orrvérzés és vízhólyag kezelését."]),
    FurdesiSzabalyok: new Alproba("Fürdési szabályok", ["Ismered a fürdési szabályokat (6 db.)."]),
    TizErdeiAllat: new Alproba("10 erdei állat", ["Ismersz 10 erdei állatot, nyomát és életmódját. MO: vaddisznó,őz,róka,nyúl,egér,mókus,borz,nyest,sün és a medve."]),
    HaromszalasFonas: new Alproba("Háromszálas fonás", ["Készítesz dísztárgyat háromszálas fonással."]),
    RovasirasAlapok: new Alproba("Rovásírás alapok", ["Ismered a rovásírás szabályait és eredetét.", "Fejből le tudod írni saját nevedet rovásírással."]),
    TizLegfontosabbTerkepjel: new Alproba("10 legfontosabb térképjel", ["Megtanulod: erdő, vasút, templom, folyó, főút, út, ösvény, épület, torony, tó térképjeleit."]),
    Menetszabalyok: new Alproba("Menetszabályok", ["Tudod a menetszabályokat (5db.)."]),
    MegfigyeloJatek: new Alproba("Megfigyelő játék", ["Ismersz 3 Kim-játékot."]),
    BaltaEsFureszHasznalata: new Alproba("Balta és fűrész használata", ["Baltát és fűrészt szabályosan tudsz használni.", "Helyesen tudod azokat vinni és átadni."]),
    Tuzszabalyok: new Alproba("Tűzszabályok", ["El tudod mondani a tűzgyújtási szabályokat (5db.).", "Tudsz szabályosan tüzet rakni és meggyújtani."]),
    Gyakorlatok5FontosSzabaly: new Alproba("Gyakorlatok", ["Ismered a számháború 5 fontos szabályát.", "Részt vettél 3 vasgyúró játékon."]),
    UgyessegKuszas: new Alproba("Ügyesség", ["Tudsz zaj nélkül kúszni és lopózkodni."]),
    Kitartas3PercFutas: new Alproba("Kitartás", ["Tudsz 3 percig futni (vagy 50 métert úszni, vagy 4 km-t kerékpározni)."]),
    Csapat: new Alproba("Csapat", ["Ismered a csapatod számát és névadóját."]),
    Vezetok: new Alproba("Vezetők", ["Tudod a cspk-d és őv-d nevét és tel. számát."]),
    Cserkeszrangok: new Alproba("Cserkészrangok", ["Ismered a cs. rangok sorrendjét és jelvényeit."]),
    BiPi: new Alproba("BiPi", ["Ismered BiPi rendes nevét."]),
    Templom: new Alproba("Templom", ["Ismered a templom berendezését és külső jeleit."]),
    EgyhaziEnekek: new Alproba("Egyházi énekek", ["Tudsz 2 egyházi éneket."]),
    CserkesztorvenyOtEsHat: new Alproba("Cserkésztörvény 5. & 6.", ["Saját szavaiddal és példával el tudod magyarázni."]),
    Jellemvonasok: new Alproba("Jellemvonások", ["Tudsz példát mondani a következő tulajdonságokra: árulkodás, hazudás, bátorság, őszinteség."]),
    KiszamoloVers: new Alproba("Kiszámoló vers", ["El tudsz mondani legalább két kiszámoló verset."]),
    HonfoglalasiMondak: new Alproba("Honfoglalási mondák", ["El tudsz mondani 2 honfoglalási mondát."]),
    Tortenelem859Tol: new Alproba("Történelem 859 -", ["Tudod, hogy ki volt Árpád vezér?", "Tudod mi volt a vérszerződés és a honfoglalás."]),
    FoldrajzKarpatHegy: new Alproba("Földrajz:", ["Ismered a Kárpátmedence vizeit (10) és hegyeit (5)."]),
    HaromszoguKendo: new Alproba("Háromszögű kendő", ["Használni tudod kéz, kar, láb és fej bekötésére."]),
    EgesEsNapszuras: new Alproba("Égés és napszúrás", ["Tudod mit kell tenni égésnél és napszúrásnál."]),
    EgyeniHigieniaMosakodas: new Alproba("Egyéni higiénia", ["Tudsz lavórban mosakodni (Tetőtől talpig!).", "Csajkádat rendesen el tudod mosogatni."]),
    TizFaIsmerete: new Alproba("10 fa ismerete.", ["Megismered kinézetéről (levél, virág, stb.) és tudod, hogy mire jó.", "( MO: bükk, tölgy, akác, nyír, hárs, lucfenyő és vörösfenyő, alma, dió, cseresznye)"]),
    Hurkok: new Alproba("Hurkok", ["Használni tudod az egyszerű állóhurkot, sváb hurkot és a csúszó hurkot."]),
    RovasirasNeved: new Alproba("Rovásírás", ["Rovásírással felhímzed vagy faragod a nevedet."]),
    Terkepfajtak: new Alproba("Térképfajták", ["Ismered a városi- és autó-térkép sajátosságait, valamint ha körzetedben ismert, a turistatérképét."]),
    EszakIranyIranytuvel: new Alproba("Észak irány iránytűvel", ["Iránytűvel pontosan megmutatod észak irányát."]),
    HolVagyATerkepen: new Alproba("Hol vagy a térképen?", ["Felismered, hogy hol állsz a térképen."]),
    TerkepMeretarany: new Alproba("Térkép méretarány", ["Tudod mit jelent 1:25 000, 1:50 000, 1:100 000."]),
    TerkepBetajolas: new Alproba("Térkép betájolás", ["Betájolod a térképet észak irányába."]),
    AlapmeretekBecslese: new Alproba("Alapméretek becslése", ["10 % pontossággal megmondod, hogy mennyi 1m, 10 cm (vagy 1 láb, egy yard, 1 hüvelyk)."]),
    KisSator: new Alproba("Kis sátor (vagy őrsi sátor)", ["Fel tudod állítani, lebontani és becsomagolni."]),
    Satorcovek: new Alproba("Sátorcövek", ["Tudsz cöveket beverni, faragsz fából pótcöveket."]),
    SzemelyesCsomagolas: new Alproba("Személyes csomagolás", ["Hátizsákot csomagolsz egy hétvégére.", "Írd fel az egyéni felszerelési tárgyak listáját."]),
    Satorrend: new Alproba("Sátorrend", ["Sátorban is rendben tudod tartani a dolgaidat."]),
    TuzeloFak: new Alproba("Tüzelő fák", ["Ismered és gyűjtesz tüzelésre alkalmas fákat.", "Tudod mi a gyújtós."]),
    Gyakorlatok2NepiJatek: new Alproba("Gyakorlatok", ["Bemutatsz 2 népi körjátékot és 3 labdajátékot."]),
    UgyessegNyil: new Alproba("Ügyesség", ["Íjjal és nyíllal célba lősz."]),
    Kitartas4PercetFutni: new Alproba("Kitartás", ["Tudsz 4 percet futni, (vagy 100 métert úszni, vagy 6 km-t kerékpározni)."]),
    KMCsSzKeruletek: new Alproba("KMCsSz - kerületek", ["Ismered körzetedet, kerületedet és a Szövetséget."]),
    ACserkeszetRendje: new Alproba("A cserkészet rendje", ["Tudod, hogy mi az őrsi rendszer alapgondolata."]),
    VallasiIsmeretek: new Alproba("Vallási ismeretek", ["Jézus életéből ismersz egy példát.", "Tudsz papoknak helyesen köszönni.", "Első áldozás, bérmálás és konfirmálás."]),
    CserkesztorvenyHetEsNyolc: new Alproba("Cserkésztörvény 7. & 8.", ["Saját szavaiddal és példával el tudod magyarázni."]),
    ViselkedesIllemszabalyok: new Alproba("Viselkedés, illemszabályok", ["Tudod, hogyan kell viselkedni társaságban, idősebbekkel szemben, étkezésnél, stb."]),
    NemzetiUnnepek: new Alproba("Nemzeti ünnepek", ["Ismersz 3 nemzeti ünnepet."]),
    CsaladiUnnepek: new Alproba("Családi ünnepek", ["Ismered a családi ünnepeket (5)."]),
    Tortenelem1000Tol: new Alproba("Történelem 1000 -", ["Ismered Géza fejedelem és Szent István tetteit."]),
    FoldrajzDunantulVaros: new Alproba("Földrajz", ["Dunántúl: Jellegzetességei, főbb városai, stb."]),
    Csipes: new Alproba("Csípés", ["Tudod, hogy csípésnél mit kell tenni."]),
    Kullancs: new Alproba("Kullancs", ["Tudod, hogy mit csinálsz kullancscsípésnél."]),
    GyomorrontasHanyas: new Alproba("Gyomorrontás, hányás", ["Tudod kezelni a hasfájást, hányást, hasmenést."]),
    Mergezes: new Alproba("Mérgezés", ["Tudod, hogy mérgezésnél mit kell tenni."]),
    OtHelyiMadar: new Alproba("5 helyi madár", ["Ismersz 5 madarat repülésben és az életmódját. (MO: gólya, bagoly, veréb, rigó és fecske)"]),
    HaromRagadozoMadar: new Alproba("3 ragadozó madár", ["Ismered árnyékképét repülésben és az életmódját (MO: egerészölyv, kánya és sólyom)"]),
    Kotelletra: new Alproba("Kötéllétra", ["Tudod, hogy melyik csomó kell a kötéllétrához.", "Tudsz egy kötéllétrát építeni."]),
    KotelFeltekeres: new Alproba("Kötél feltekerés", ["Kötelet helyesen fel tudsz szedni (tekerni)."]),
    RovasirasAbc: new Alproba("Rovásírás", ["Fejből tudod a rovásírás abc-t."]),
    EszakiIranyIranytuNelkul: new Alproba("Északi irány iránytű nélkül", ["Ismersz 3 módot az északi irány megállapítására. (Nap és óra, Nap és árnyék, Göncölszekér vagy Dél keresztje)."]),
    TajoloHasznalata: new Alproba("Tájoló használata", ["Iránytűvel bármilyen irányt meg tudsz állapítani."]),
    Arak: new Alproba("Árak", ["Becsüld meg egyes tárgyak bolti árát. (5db)."]),
    PenzBeosztasa: new Alproba("Pénz beosztása", ["Minél olcsóbban uzsonnát veszel az őrsödnek."]),
    ZsebkesElesites: new Alproba("Zsebkés", ["Megélesíted a zsebkésedet."]),
    Csajkazsak: new Alproba("Csajkazsák", ["Varrsz egy csajkazsákot."]),
    Teafozes: new Alproba("Teafőzés", ["Építesz olyan főzőalkalmatosságot, amin teát főzöl."]),
    Gyakorlatok3Korjatek: new Alproba("Gyakorlatok", ["Bemutatsz társaiddal 3 körjátékot."]),
    UgyessegKotelLetra: new Alproba("Ügyesség", ["Tudsz kötéllétrán mászni.", "Elvégzel egyensúlygyakorlatokat."]),
    Kitartas5PercFutas: new Alproba("Kitartás", ["Tudsz 5 percet futni (vagy 200 métert úszni, vagy 8 km-t kerékpározni)."]),
    Cserkesztortenelem: new Alproba("Cserkésztörténelem", ["Ismered Bipi életét és főbb jelszavait.", "Ismered a cserkésztörténet főbb eseményeit (1907, 1933, 1948).", "Ismered a leánycserkészet történetét (Pax Ting)."]),
    SzabadImadkozas: new Alproba("Szabad imádkozás", ["Tudsz saját szavaiddal imádkozni."]),
    CserkesztorvenyKilencEsTiz: new Alproba("Cserkésztörvény 9. & 10.", ["Saját szavaiddal és példával el tudod magyarázni."]),
    TaborozasiSzabalyok: new Alproba("Táborozási szabályok", ["Ismered a táborozási szabályokat (7 db)."]),
    HuszmagyarNepdal: new Alproba("20 magyar népdal", ["20 népdalt fel tudsz sorolni és kérésre elénekelni."]),
    Zaszlok: new Alproba("Zászlók", ["Ismersz 3 történelmi zászlót."]),
    Tortenelem1241Tol: new Alproba("Történelem 1241 -", ["Tatárjárás, IV. Béla és a második honalapítás."]),
    FoldrajzDelvidekVaros: new Alproba("Földrajz", ["Délvidék: Jellegzetességei, főbb városai, stb."]),
    Hordagy: new Alproba("Hordágy", ["Tudsz hordágyat készíteni és használni."]),
    Nyomontes: new Alproba("Nyomöntés", ["Tudsz gipsszel állatnyomot önteni."]),
    Nyomolvasas: new Alproba("Nyomolvasás", ["Találsz nyomokat és tudod azokat követni."]),
    Allatmegfigyeles: new Alproba("Állatmegfigyelés", ["Szabadban figyelj meg 3 állatot."]),
    Keresztkotes: new Alproba("Keresztkötés", ["A keresztkötést meg tudod kötni."]),
    KotelKarbantartasa: new Alproba("Kötél karbantartása", ["Tudsz kötelet tárolni, tisztítani és szárítani."]),
    NyolcUtjelKobolEsFubol: new Alproba("8 útjel kőből és fűből", ["Jó út, rossz út, hazamentem, menj haza, jó víz, rossz víz, levél x lépésre, vigyázz / veszély."]),
    VarosterkepHasznalata: new Alproba("Várostérkép használata", ["Városban közlekedsz, adott helyeket megtalálsz."]),
    TerkepEsIranytuEgy: new Alproba("Térkép és iránytű 1.", ["Térkép alapján be tudod tájolni a menetirányt."]),
    AsoCsakany: new Alproba("Ásó, csákány", ["Használod és rendben elrakod (zsírozás)."]),
    TaboriHigieniaLatrina: new Alproba("Tábori higiénia", ["Tudsz szabályos latrinát /pöcegödröt építeni."]),
    PonyvaHasznalata: new Alproba("Ponyva használata", ["Építesz ponyvából védőhelyet."]),
    EgyszeruTaboriEpitmeny: new Alproba("Egyszerű tábori építmény", ["Készítesz 1 tábori építményt (csajkafa, mosdó)."]),
    Tuzfajtak: new Alproba("Tűzfajták", ["Megrakod a gúla, máglya, és vadásztüzet.", "Ezekből az egyiket max. 3 gyufával meggyújtod."]),
    Gyakorlatok2NepiJetek: new Alproba("Gyakorlatok", ["Bemutatsz 2 népi csoport játékot és 3 kötél játékot. "]),
    UgyessegMeneteles: new Alproba("Ügyesség", ["Tudod mi a cserkészmenetelés és alkalmazod."]),
    Kitartas6PercFutas: new Alproba("Kitartás", ["Tudsz 6 percet futni (vagy 300 métert úszni, vagy 10 km-t kerékpározni)."]),
    CserkesztortenelemTeleki: new Alproba("Cserkésztörténelem", ["Tudod ki volt Gróf Teleki Pál és mi a hagyatéka."]),
    Cserkeszszolgalat: new Alproba("Cserkészszolgálat", ["Tudod, hogy mi a cserkészszolgálat és őrsöddel cserkészszolgálatot tettél."]),
    Kereszteles: new Alproba("Keresztelés", ["Tudod, hogy mit jelent és mi a célja a keresztelésnek."]),
    DohanyzasEsAlkohol: new Alproba("Dohányzás és alkohol", ["Részt vettél cigarettáról és alkoholról szóló vitán.", "(cs. törvény, tábori szabályok összefüggésében)"]),
    Nepdal30: new Alproba("Népdal", ["Ismersz 30 népdalt és kérésre el tudod énekelni"]),
    OthiresMagyar: new Alproba("5 híres magyar", ["Ismersz 5 híres magyar személyt, és mesélni tudsz róla.(pl. feltaláló, utazó, művész, egyéb ...)"]),
    Tortenelem1301Tol: new Alproba("Történelem 1301 -", ["Anjou dinasztia: Károly Róbert és Nagy Lajos"]),
    FoldrajzAlfoldVaros: new Alproba("Földrajz", ["Alföld: Jellegzetességei, főbb városai, stb."]),
    BalesetMegelozese: new Alproba("Baleset megelőzése", ["Tudsz 3 példát mondani a baleset elkerüléséhez."]),
    FelhokEsJelentesuk: new Alproba("Felhők és jelentésük", ["Ismersz 4 felhőfajtát és hogy mit jelentenek. (bárány-, réteg- fátyol- és viharfelhő)"]),
    Idojaras: new Alproba("Időjárás", ["Ismered a helyi időjárási viszonyokat."]),
    Idojoslasok: new Alproba("Időjóslások", ["Ismersz népi időjóslásokat (4db)."]),
    EgyMentocsomo: new Alproba("1 Mentőcsomó", ["Egy mentőcsomót biztosan meg tudsz kötni."]),
    FaramaszasHurokkal: new Alproba("Fáramászás hurokkal", ["Tudsz hurok segítségével fára mászni."]),
    TitkosIrasok: new Alproba("Titkos írások", ["4 titkos írás:(pl. betűcsere, tükörírás, 5x5 kocka, Morze)", "Titkos írás citrommal."]),
    MegTizTerkepjel: new Alproba("Még 10 térképjel", ["Ismered és térképen megmutatod: vezeték, híd, mocsár, bokrok, egyes fák, sziklák, határok, forrás, barlang, temető."]),
    MagassagiSzintvonalak: new Alproba("Magassági szintvonalak", ["Tudod,hogy mit jelentenek, értelmüket és távolságukat."]),
    HelyrajziTerkep: new Alproba("Helyrajzi térkép", ["Eltalálsz a célba helyrajzi térkép segítségével."]),
    Ido: new Alproba("Idő", ["1 perc hosszát megbecsülöd.", "Nap állásából megbecsülöd, hogy hány óra van."]),
    Szerszamtarto: new Alproba("Szerszámtartó", ["Építesz egy tábori szerszámtartót."]),
    BaltaKarbantartasa: new Alproba("Balta karbantartása", ["Megélesítesz egy baltát, laza fejét javítani tudod."]),
    FureszKarbantartasa: new Alproba("Fűrész karbantartása", ["Rossz fűrészlapot kicserélsz és bezsírozol."]),
    SutesFoliaban: new Alproba("Sütés fóliában", ["Parazsat készítesz és fóliában sütsz benne."]),
    Gyakorlatok3Erogyakorlat: new Alproba("Gyakorlatok", ["Bemutatsz 3 erőgyakorlatot."]),
    Kitartas7PercFutas: new Alproba("Kitartás", ["Tudsz 7 percet futni (vagy 400 métert úszni, vagy 12km-t kerékpározni)."]),
    CserkesztortenelemSik: new Alproba("Cserkésztörténelem", ["Tudod ki volt Sík Sándor és tudsz tőle idézni."]),
    Forum: new Alproba("Fórum", ["Tudod, hogy mi a Magyar Cserkészszövetségek Fóruma és, hogy kik a tagjai (8)."]),
    EgyhaziUnnepek: new Alproba("Egyházi ünnepek", ["Ismersz 4 egyházi ünnepet és időpontját."]),
    TvMobiltelefonJatek: new Alproba("TV - mobiltelefon - játék", ["Részt vettél vitán ezekről a témákról."]),
    Csalad: new Alproba("Család", ["Őrsöddel részt vettél egy beszélgetésen szülő-gyermek viszonyáról. (lásd Lcs. könyv II. 14. oldal)"]),
    Nepdal40: new Alproba("Népdal", ["Ismersz 40 népdalt és kérésre el tudod énekelni."]),
    MagyarUtazok: new Alproba("Magyar utazók", ["Ismersz 2 utazót és tudod, hogy merre jártak."]),
    MatyasKiralyMondak: new Alproba("Mátyás király mondák", ["El tudsz mondani 2 mondát Mátyás királyról."]),
    TizenotSzazad: new Alproba("15. század", ["Ki voltHunyadi János és Hunyadi Mátyás?"]),
    FoldrajzKarpataljaVaros: new Alproba("Földrajz", ["Kárpátalja: jellegzetességei, főbb városai, stb."]),
    FicamodasEsRandulas: new Alproba("Ficamodás és rándulás", ["Ellátsz egy megrándult vagy kificamodott bokát."]),
    SebesultSzallitas: new Alproba("Sebesült szállítás", ["Tudsz sebesültet hordágy nélkül vinni."]),
    EhetoNovenyek: new Alproba("Ehető növények", ["Ismersz 5 helyi ehető, vadon élő növényt. ( MO: szeder, málna, csipke, bodza és áfonya)"]),
    MergezoNovenyek: new Alproba("Mérgező növények", ["Ismersz 3 helyi mérgező növényt és káros hatását. (MO: Gyöngyvirág, tiszafa és nadragulya)"]),
    Viragok: new Alproba("Virágok", ["Ismersz 5 nálatok honos virágot. (MO: pitypang, százszorszép, ibolya, pipacs és napraforgó )"]),
    ParhuzamosKotes: new Alproba("Párhuzamos kötés", ["Meg tudod kötni a párhuzamos kötést.", "Tudsz 3-lábat építeni párhuzamos kötéssel."]),
    Veszjelek: new Alproba("Vészjelek", ["Füsttel, Síppal (SOS), tükör, helyi vészjelek."]),
    UtiranyBetartasaIranytuvel: new Alproba("Útirány betartása iránytűvel", ["Iránytűvel becélzott irányt tartod menet közben."]),
    IranyAtviteleTerkepre: new Alproba("Irány átvitele térképre", ["Egy becélzott irányt iránytűvel átviszel térképre."]),
    Tavolsagbecsles: new Alproba("Távolságbecslés", ["Nagyobb távolságot tudsz 10% pontossággal becsülni: (arc, ember, embercsoport segítséggel).", "Távolságbecslés (pl. hüvelykujjal)."]),
    PetroleumLampa: new Alproba("Petróleum lámpa", ["Biztonságos használata, üvegcsere, kanóc csere."]),
    Gazlampa: new Alproba("Gázlámpa", ["Biztonságos használata, palack- és harisnya csere."]),
    FozesBogracsban: new Alproba("Főzés bográcsban", ["Elkészítesz egy egyszerű ételt bográcsban."]),
    Gyakorlatok3Hajlekony: new Alproba("Gyakorlatok", ["Bemutatsz 3 hajlékonysági gyakorlatot."]),
    Meta: new Alproba("Méta", ["Ismered a métát."]),
    Kitartas8PercFutas: new Alproba("Kitartás", ["Tudsz 8 percet futni (vagy 500 métert úszni, vagy 14 km-t kerékpározni)."]),
    CserkesztortenelemBodnar: new Alproba("Cserkésztörténelem", ["Tudod ki volt Bodnár Gábor és mit csinált."]),
    MagyarSzentek: new Alproba("Magyar szentek", ["El tudod mondani 3 magyar szent 1-1 legendáját."]),
    Kabitoszer: new Alproba("Kábítószer", ["Részt vettél beszélgetésen a kábítószerről (a cs. törvény és szabályzat, valamint országod törvényének ismeretében)."]),
    Segitokeszseg: new Alproba("Segítőkészség", ["Segítesz öregeknek (pl. Templomban, öregotthonban)."]),
    Takarekossag: new Alproba("Takarékosság", ["Részt vettél beszélgetésen a pénzzel való gazdálkodásról és arról beszámolsz."]),
    Nepdal50: new Alproba("Népdal", ["Ismersz 50 népdalt."]),
    MagyarVarakTortenete: new Alproba("Magyar várak története", ["Ismered 3 magyar vár történetét."]),
    MagyarSportolok: new Alproba("Magyar sportolók", ["Ismersz 2 sikeres magyar sportolót."]),
    Tortenelem1526Tol: new Alproba("Történelem 1526-", ["Mesélj a mohácsi vészről, a török korszakról és a végvári harcokról (Eger, Szigetvár, ...)."]),
    FoldrajzOrsegVaros: new Alproba("Földrajz", ["Őrség: Jellegzetességei, főbb városai, stb."]),
    VerzesFajtak: new Alproba("Vérzés fajták", ["Ismered a 3 vérzésfajtát és a teendőket."]),
    Allatharapasok: new Alproba("Állatharapások", ["Tudod, hogy állatharapásnál mit kell tenni."]),
    Mentodoboz: new Alproba("Mentődoboz", ["Ismered az őrsi mentődoboz tartalmát."]),
    OtVedettAllat: new Alproba("5 védett állat", ["Ismersz 5 helyi védett állatot és az életmódját. (MO: vízisikló, denevér, gyík, hód, hiúz)"]),
    Allatfenykepezes: new Alproba("Állatfényképezés", ["Lesből fényképezz erdei állatot."]),
    DisztargyakNyakkendo: new Alproba("Dísztárgyak", ["Nyakkendő gyűrűt fonsz egy kiscserkésznek."]),
    OldalEsKeresztmetszes: new Alproba("Oldal-, és keresztmetszés", ["Tudod az oldalmetszést, és hogy mire való.", "Ismered a keresztmetszést és hogy mire való."]),
    Mennyisegek: new Alproba("Mennyiségek", ["Becsülj 5 különböző mennyiséget (pl. hány ember van egy teremben, menyi víz van egy tartályban)."]),
    NagySator: new Alproba("Nagy sátor", ["Felverés, bontás és csomagolás. Pl. konyhasátor.", "Sátorjavítás, szárítás, tárolás."]),
    Tuzvedelem: new Alproba("Tűzvédelem", ["Tudod, mit kell tenni tűz esetén (5)."]),
    Gyakorlatok3Lazito: new Alproba("Gyakorlatok", ["Bemutatsz 3 lazító gyakorlatot."]),
    Kitartas9PercFutas: new Alproba("Kitartás", ["Tudsz 9 percet futni (vagy 600 métert úszni, vagy 16 km-t kerékpározni)."]),
    HontalanSasok: new Alproba("Hontalan Sasok", ["Tudod kik voltak a Hontalan Sasok és szerepüket."]),
    Vezetokepzes: new Alproba("Vezetőképzés", ["Ismered a KMCSSZ VK-rendszerét. Tudod mik a feltételek."]),
    KotelessegunkIstenne: new Alproba("Kötelességünk Istenne", ["El tudod magyarázni a cs. törvény 2. pontját „... kötelességét, mellyel Istennek ... tartozik”."]),
    Szerelem: new Alproba("Szerelem", ["Részt vettél beszélgetésen a szerelemről (a Biblia szerint, a mai társadalomban, filmben, stb.)."]),
    Baratsag: new Alproba("Barátság", ["Őrsöddel részt vettél beszélgetésen a Barátságról. (lásd Lcs. könyv II-70. oldal)"]),
    Nepdal60: new Alproba("Népdal", ["Ismersz 60 népdalt."]),
    MagyarTalalmanyok: new Alproba("Magyar találmányok", ["Ismersz 2 nagy magyar találmányt és feltalálóját."]),
    TortenelemErdelyAranykor: new Alproba("Történelem", ["Erdély aranykora: Bethlen, Bocskai, Báthory", "A 3 részre szakadt ország."]),
    FoldrajzErdelyVaros: new Alproba("Földrajz", ["Erdély: Jellegzetességei, főbb városai, stb."]),
    Elsosegelynyujtas: new Alproba("Elsősegélynyújtás", ["Tudsz elsősegélyt nyújtani az „1,2,3” szerint. (1 légzés, 2 vérzések, 3 vérkeringés)."]),
    SinbeRakas: new Alproba("Sínbe rakás", ["Tudsz eltört ujjat, kart vagy lábat sínbe rakni."]),
    FeherEsVorosAjulas: new Alproba("Fehér és vörös ájulás", ["Ismered az ájulási fajtákat (2), mi a teendő?"]),
    SOKK: new Alproba("SOKK", ["Az életveszélyes állapot felismerése és kezelése."]),
    Oldalfektetes: new Alproba("Oldalfektetés", ["Tudod, mikor kell a stabil oldalfekvést használni."]),
    VedettNovenyek: new Alproba("Védett növények", ["Ismersz 3 helyi védett növényt. (MO: encián, árvalányhaj, kankalin)"]),
    TermeszetvedelmiTeruletek: new Alproba("Természetvédelmi területek", ["Ismered a természetvédelmi területeken érvényes szabályokat."]),
    Kotelhid: new Alproba("Kötélhíd", ["Feszítőcsomó kötélhídhoz.", "Ácshurok."]),
    UtvonalTervezes: new Alproba("Útvonal tervezés", ["Térképen kiválasztod a legjobb portya útvonalat."]),
    LeptekAtszamolas: new Alproba("Lépték átszámolás", ["Tudod, hogy pl. 4 cm az 1:50'000 térképen mennyi távolság a valóságban, és fordítva."]),
    OnméretekIsmetleseEsHasznalata: new Alproba("Önméretek ismétlése és használata", ["Saját méreteidet ismered: kis-, és nagy arasz, hüvelykujj, testmagasság, fesztáv, 1 lépés, láb. Hány lépés 100 m (vagy 100 yard)?"]),
    Gaztuzhely: new Alproba("Gáztűzhely", ["Gáz zsámolyt helyesen be tudsz gyújtani."]),
    SutesKenyer: new Alproba("Sütés", ["Sütöttél kenyeret / pogácsát sütőben vagy tűzön."]),
    FinomsagokTuzon: new Alproba("Finomságok tűzön", ["Sütsz egy finomságot tűzön."]),
    Gyakorlatok2Kitartas: new Alproba("Gyakorlatok", ["Bemutatsz 2 kitartási gyakorlatot."]),
    UgyessegCsoportos: new Alproba("Ügyesség", ["Ismersz 2 csoportos játékot."]),
    Kitartas10PercFutas: new Alproba("Kitartás", ["Tudsz 10 percet futni (vagy 700 métert úszni, vagy 18 km-t kerékpározni)."]),
    ATizParancsolatSzovege: new Alproba("A 10 parancsolat szövege", ["Ismered a 10 parancsolat szövegét."]),
    VallasosBeszelgetes: new Alproba("Vallásos beszélgetés", ["Részt vettél vallásos témájú beszélgetésen.", "(lásd Lcs. könyv II.- 184 oldal)"]),
    CserkesziesViselkedesReszlet: new Alproba("Cserkészies viselkedés", ["Példával részletezd: segítőkész, lusta."]),
    VitaTargyilakos: new Alproba("Vita", ["Tudsz vitában tárgyilagosan érvelni."]),
    Nepdal70: new Alproba("Népdal", ["Ismersz 70 népdalt."]),
    MagyarFesto: new Alproba("Magyar festő", ["Ismersz 2 festőt és leghíresebb képeiket."]),
    NyelvtaniJatekok: new Alproba("Nyelvtani játékok", ["Készítesz nyelvtani játékot."]),
    TortenelemRakoci: new Alproba("Történelem", ["II. Rákóczi Ferenc és a kuruc kor."]),
    FoldrajzFelvidekVaros: new Alproba("Földrajz", ["Felvidék: Jellegzetességei, főbb városai, stb."]),
    Ivovizkeszites: new Alproba("Ivóvízkészítés", ["Tudsz ivóvizet készíteni (szűrni, forralni)."]),
    EgészsegesEtkezes: new Alproba("Egészséges étkezés", ["Tudod hogyan kell egészségesen táplálkozni."]),
    EgyeniHigieniaRuha: new Alproba("Egyéni higiénia", ["Táborban kimosod a ruhádat."]),
    Csillagkepek: new Alproba("Csillagképek", ["Ismersz 8 csillagképet és legendáját."]),
    KotelvegEldolgozas: new Alproba("Kötélvég eldolgozás", ["Kötélvég eldolgozása (2 mód)."]),
    Kotelfajtak: new Alproba("Kötélfajták", ["Ismersz 3 kötélfajtát és hogy mire jók."]),
    TajekozodasNapEsCsillag: new Alproba("Tájékozódás Nap és csillag", ["Tudsz a Nap és a csillagok segítségével tájékozódni."]),
    Haromszogeles: new Alproba("Háromszögelés", ["Magasság és folyó szélességének megállapítása."]),
    TaboriHigieniaTaborozas: new Alproba("Tábori higiénia", ["Tudod, hogy mire kell táborozásnál ügyelni."]),
    Illesztes: new Alproba("Illesztés", ["Tudsz fűrésszel és baltával fákat illeszteni."]),
    MaglyatuzMegrakasa: new Alproba("Máglyatűz megrakása", ["Megraktál és tápláltál egy tábortüzet."]),
    KulonlegesGyujtasmodok: new Alproba("Különleges gyújtásmódok", ["Bemutatsz egy különleges gyújtásmódot."]),
    Bemelegites: new Alproba("Bemelegítés", ["Tudsz bemelegítő gyakorlatokat és tudod, hogy mire jók."]),
    ReggeliTorna: new Alproba("Reggeli torna", ["Vezetsz egy reggeli tornát (kb. 10 perc)."]),
    Kitartas11PercFutas: new Alproba("Kitartás", ["Tudsz 11 percet futni (vagy 800 métert úszni, vagy 20 km-t kerékpározni)."]),
    MagyarCserkeszet: new Alproba("Magyar cserkészet", ["Ismered a magyar cserkészet történetét."]),
    HelyiMagyarsag: new Alproba("Helyi magyarság", ["Ismered a helyi magyarság történetét."]),
    HelyiCserkeszetMagyar: new Alproba("Helyi cserkészet", ["Ismered a helyi magyar cserkészet történetét és főbb vezetőit."]),
    Lelkigyakorlatok: new Alproba("Lelkigyakorlatok", ["Csendes elmélkedésen veszel részt."]),
    Szentiras: new Alproba("Szentírás", ["Ismered a Biblia felépítését (Ószövetség, Újszövetség, négy evangélista, ...)."]),
    CserkesziesViselkedesElmond: new Alproba("Cserkészies viselkedés:", ["Példával elmondod, hogy mi a „megbízhatóság”.", "Példával elmondod, hogy mi az „önmegtartóztatás”."]),
    Eloadas: new Alproba("Előadás", ["Előadást tartasz (őrsödnek, csapatodnak, tábornak) egy általad választott témáról."]),
    KotelessegtudatHaza: new Alproba("Kötelességtudat", ["Példákkal elmondod, hogy mi a kötelességünk a hazával és a magyarsággal szemben (fogadalom)."]),
    Nepdalok: new Alproba("Népdalok", ["Ismersz 80 népdalt."]),
    MagyarKoltok: new Alproba("Magyar költők", ["Ismersz 4 híres költőt és egy-egy művét."]),
    Versmondas: new Alproba("Versmondás", ["Szavaltál egy komoly verset. (szavalóverseny)."]),
    Tortenelem1848: new Alproba("Történelem", ["Ismered az 1848-as szabadságharc történetét."]),
    FoldrajzKisalfoldVaros: new Alproba("Földrajz", ["Kisalföld: Jellegzetességei, főbb városai, stb."]),
    NepiGyogyaszat: new Alproba("Népi gyógyászat", ["Ismersz házi recepteket (3)."]),
    Mentes: new Alproba("Mentés", ["Tudod, hogyan kell menteni jégből, tűzből és ha valakit áramütés ért."]),
    Gyogynovenyek: new Alproba("Gyógynövények", ["Ismersz 5 gyógynövényt és alkalmazásukat."]),
    GPS: new Alproba("GPS", ["Ismered a GPS működését."]),
    Geocaching: new Alproba("„Geocaching”", ["Eldugsz vagy megkeresel egy tárgyat."]),
    TizAlapmeretek: new Alproba("10 alapméretek", ["Becslést segítő méreteket ismersz. (pl. emelet, ingalengés, fa magassága, focipálya hossza, pénz mérete, stb.)"]),
    TaboriEpitmenyek: new Alproba("Tábori építmények", ["Készítesz 1 nagy tábori építményt (pl. őrsi kaput, altábori kaput, vagy tábori konyhát.)."]),
    BiwakAlvohelyEpites: new Alproba("Biwak (alvóhely) építés", ["Sátor nélkül kint alszol saját magad építette alvóhelyedben."]),
    HaromFogasosEtelTuzon: new Alproba("3 fogásos étel tűzön", ["Készítesz 3-fogásos ételt tűzön vagy gázon."]),
    Ijaszat: new Alproba("Íjászat", ["Tudsz íjjal célba lőni."]),
    Kitartas12PercFutas: new Alproba("Kitartás", ["Tudsz 12 percet futni (vagy 900 métert úszni, vagy 25 km-t kerékpározni)."]),
    HelyiCserkeszetNemzetkozi: new Alproba("Helyi cserkészet", ["Ismered a helyi cserkészetet. (pl. egyenruha, szokások)"]),
    VilagcserkeszetMa: new Alproba("Világcserkészet ma", ["Hány cserkész van, utolsó Jamboree-k, WOSM."]),
    EtikaiAlapelvek: new Alproba("Etikai alapelvek", ["Részt vettél etikai elvekről való beszélgetésen."]),
    CserkesziesViselkedesJellemzes: new Alproba("Cserkészies viselkedés", ["Mi jellemezi az igazi cserkészies viselkedést.", "Kiscserkészeknek bábozol erről."]),
    VitaLogikus: new Alproba("Vita", ["Vitában logikusan tudsz érvelni."]),
    KotelessegtudatEmber: new Alproba("Kötelességtudat", ["Példával elmondod, hogy mi a kötelességünk embertársainkkal szemben (fogadalom)."]),
    Nepdal90: new Alproba("Népdal", ["Ismersz 90 népdalt."]),
    MagyarZeneszerzok: new Alproba("Magyar zeneszerzők", ["Ismersz 2 híres zeneszerzőt."]),
    Cikkiras: new Alproba("Cikkírás", ["Írsz egy cikket, pl. újságba/ honlapra."]),
    TortenelemVilaghaboru: new Alproba("Történelem", ["Ismered Magyarország szerepét az I. és II. világháborúban."]),
    FoldrajzTrianon: new Alproba("Földrajz", ["Ismered a Trianoni békekötés következményeit."]),
    Kigyoharapas: new Alproba("Kígyóharapás", ["Tudod, hogyan kell kígyóharapást kezelni."]),
    MestersegesLegzes: new Alproba("Mesterséges légzés", ["Tudsz mesterséges légzést adni."]),
    TizHelyiRovarEsHullo: new Alproba("10 helyi rovar és hüllő", ["Ismered nevüket és tudod, hogy melyik veszélyes / védett. (MO: méh, darázs, szitakötő, szarvasbogár, pók, béka, varangy, gyík, vipera, skorpió)"]),
    TermeszetvedelemKezdemeny: new Alproba("Természetvédelem", ["Részt veszel egy természetvédelmi kezdeményezésen."]),
    OtKulonlegesCsomo: new Alproba("5 különleges csomó", ["Pruszik, ívelt kettős, nyolcas hurok, tolvaj csomó, kötélrövidítő."]),
    TerepfelméresTerkeppel: new Alproba("Terepfelmérés térképpel", ["Térkép alapján eldöntöd, hogy hol jó sátrat verni.", "A terepen kiválasztod a jó sátorhelyet."]),
    Terkepvazlat: new Alproba("Térképvázlat", ["Tudsz helyes térképvázlatot / látrajzot készíteni."]),
    PenzBeosztas: new Alproba("Pénz beosztás", ["Vásárolj be egy kirándulásra minél olcsóbban."]),
    PenzugyiElszamolas: new Alproba("Pénzügyi elszámolás", ["Tudsz helyesen bevételről - kiadásról elszámolni."]),
    HasznalatiTargy: new Alproba("Használati tárgy", ["Faragsz vagy varrsz egy tábori használati tárgyat."]),
    AlapElelmiszerekAdagja: new Alproba("Alap élelmiszerek adagja", ["5 alap élelmiszer személyenkénti mennyiségét ismered fejből."]),
    FozesiAdagokKiszamitasa: new Alproba("Főzési adagok kiszámítása", ["Nagy csoport számára ki tudod számítani a főzési adagokat."]),
    NepiGyakorlatok: new Alproba("Népi gyakorlatok", ["Tudsz néptáncot vagy ostorozni."]),
    Kitartas15PercFutas: new Alproba("Kitartás", ["Tudsz 15 percet futni (vagy 1000 métert úszni, vagy 30 km-t kerékpározni)."]),
    Vandorcserkeszek: new Alproba("Vándorcserkészek", ["Ismered a vándor (rover) mozgalom célját és módszerét."]),
    ZaszloterenImadkozol: new Alproba("Zászlótéren imádkozol", ["Zászló fel- vagy levonáskor mondasz saját imát."]),
    BiPiMintPelda: new Alproba("BiPi mint példa", ["Elmondod, miben lehet nekünk BiPi példa."]),
    CserkeszJovo: new Alproba("Cserkész jövő", ["Beszélgettek a cserkész jövőtökről."]),
    VitaTapintatos: new Alproba("Vita", ["Építő és tapintatos kritika."]),
    MagyarNepdal: new Alproba("Magyar népdal", ["Van listád 100 magyar népdalról és bármelyiket el is tudod énekelni."]),
    Tortenelem1956: new Alproba("Történelem", ["Ismered az 1956-os forradalom és szabadságharc történetét. Ismered Magyarország szerepét a vasfüggöny megszűnésében."]),
    ElsosegelyTanfolyam: new Alproba("Elsősegély tanfolyam", ["Végezz el egy helyi elsősegély tanfolyamot és szerezd meg a hivatalos képesítést!"]),
    Halak: new Alproba("Halak", ["Ismersz 5 halfajtát. (MO: pisztráng, csuka, harcsa, ponty, angolna.)"]),
    Csomotabla: new Alproba("Csomótábla", ["Készíts csomótáblát."]),
    Maszas: new Alproba("Mászás", ["Tudsz pruszikkal mászni."]),
    Morzejelzes: new Alproba("Morzejelzés", ["Tudsz morze üzenetet adni és fogadni morzekulcs segítségével."]),
    MenetidoSzamitas: new Alproba("Menetidő számítás", ["Portyára és kirándulásra ki tudod számítani a szükséges menetidőt, figyelembe véve a szintkülönbségeket is."]),
    Munkaido: new Alproba("Munkaidő", ["Gyakorold egy feladat elvégzéséhez szükséges idő becslését (pl. csomagolás, főzés, ...)."]),
    Taborepites: new Alproba("Táborépítés", ["Tudod, mi tartozik egy jó táborhelyhez, és hogyan lehet azt berendezni."]),
    DisztargyakNepi: new Alproba("Dísztárgyak", ["Népi dísztárgyat készítesz (faragás, hímzés, bőrmunka, fonás)."]),
    KonyhaHigienia: new Alproba("Konyha higiénia", ["Tudsz tábori konyhában tisztaságot tartani. Élelem helyes tárolása."]),
    MagyarKonyha: new Alproba("Magyar konyha", ["Ismered a magyar konyha jellegzetességeit."]),
    GyakorlatokTeljesitmeny: new Alproba("Gyakorlatok", ["Teljesítmény túrán veszel részt."]),
    UgyessegTajekozodas: new Alproba("Ügyesség", ["Részt vettél tájékozódási futáson vagy néptáncon."]),
    Kitartas20PercFutas: new Alproba("Kitartás", ["Tudsz 20 percet futni (vagy 1200 métert úszni, vagy 50 km-t kerékpározni)."]),
}

export const ProbaRendszer = new Map<Cserkesz, Map<Proba, Map<Tema, Alproba[]>>>([
    [Cserkeszek.Ujonc, new Map([
        [Probak.MagyarCimer, new Map([
            [Temak.Cserkeszismeretek, [Alprobak.AlapCserkesztudas, Alprobak.Cserkesztorveny]],
            [Temak.Vallas, [Alprobak.MindennapiImak]],
            [Temak.Jellemneveles, [Alprobak.NapiJotett]],
            [Temak.Magyarsagismeret, [Alprobak.MagyarZaszloEsLobogo, Alprobak.MagyarCimer, Alprobak.FoldrajzMagyarorszag]],
            [Temak.Elsosegely, [Alprobak.FontosAdatok]],
            [Temak.Termeszetismeret, [Alprobak.ViselkedesAzErdoben, Alprobak.OtHelyiAllat]],
            [Temak.Csomozas, [Alprobak.AlapokEsKetCsomo]],
            [Temak.Jeladas, [Alprobak.HatSipjel, Alprobak.KetKarjel]],
            [Temak.Tajekozodas, [Alprobak.SzelrozsaEsVilagtajak]],
            [Temak.Becsles, [Alprobak.TestmagassagSuly]],
            [Temak.Taborozas, [Alprobak.ZsebkesBisztonsag]],
            [Temak.Tuzrakas, [Alprobak.SutesSzabadTuzon]],
            [Temak.Testedzes, [Alprobak.Gyakorlatok3EgyeniTorna, Alprobak.UgyessegFaraMaszas, Alprobak.Kitartas1PercFutas]],
        ])],
        [Probak.SzentKorona, new Map([
            [Temak.Cserkeszismeretek, [Alprobak.CserkeszSzokasok, Alprobak.Fogadalom, Alprobak.Egyenruha, Alprobak.AlakisagokMeneteles]],
            [Temak.Vallas, [Alprobak.Ima]],
            [Temak.Jellemneveles, [Alprobak.CserkesztorvenyEgyEsKet, Alprobak.TitkosBaratBaratno]],
            [Temak.Magyarsagismeret, [Alprobak.Nepdaltudas, Alprobak.MagyarSzentKorona, Alprobak.FoldrajzKarpat]],
            [Temak.Elsosegely, [Alprobak.KisSebekKezelese]],
            [Temak.Termeszetismeret, [Alprobak.OtHelyiNoveny, Alprobak.TermeszetvedelemSzabaly]],
            [Temak.Csomozas, [Alprobak.TaborozasiCsomok]],
            [Temak.Jeladas, [Alprobak.NyolcUtjelBotbolKretaval]],
            [Temak.Tajekozodas, [Alprobak.MitKellTennedHaEltevedsz]],
            [Temak.Becsles, [Alprobak.Onmeretek]],
            [Temak.Taborozas, [Alprobak.ZsebkesNyakkendoGyuru, Alprobak.Varras]],
            [Temak.Tuzrakas, [Alprobak.HelyesGyujtas]],
            [Temak.Testedzes, [Alprobak.Gyakorlatok3ParosTorna, Alprobak.UgyessegKotelhid, Alprobak.Kitartas2PercFutas]],
        ])],
    ])],

    // [Cserkeszek.Ujonc, new Map([
    //     [Probak.SzentKorona, new Map([
    //         [Temak.Cserkeszismeretek, [Alprobak]],
    //         [Temak.Vallas, [Alprobak]],
    //         [Temak.Jellemneveles, [Alprobak]],
    //         [Temak.Magyarsagismeret, [Alprobak]],
    //         [Temak.Elsosegely, [Alprobak]],
    //         [Temak.Termeszetismeret, [Alprobak]],
    //         [Temak.Csomozas, [Alprobak]],
    //         [Temak.Jeladas, [Alprobak]],
    //         [Temak.Tajekozodas, [Alprobak]],
    //         [Temak.Becsles, [Alprobak]],
    //         [Temak.Taborozas, [Alprobak]],
    //         [Temak.Tuzrakas, [Alprobak]],
    //         [Temak.Testedzes, [Alprobak]],
    //     ])],
    // ])],
])
